### ISSUE TITLE
Comment input box bottom border not display

### ISSUE THREAD

**Issue by qingwave** [giscus/giscus#1009]
Comment input box bottom border not display, just as follow picture.

![image](https://user-images.githubusercontent.com/15335634/234273067-fcab22cc-3826-495c-a610-9d6ea022cab8.png)

Env:
os: win11 22H2
browser: Chrome 112

**Comment by qingwave** [comment]
Hi @laymonage 
Thanks for your quick replay, please check in the last of the [blog](https://qingwave.github.io/rust-ping/)

**Comment by laymonage** [comment]
Sorry, I could not replicate your issue... 
<img width="956" alt="image" src="https://user-images.githubusercontent.com/6379424/236838231-f5b19ce1-c213-467c-b551-707e7f309daf.png">

**Comment by qingwave** [comment]
Maybe it's related to env, the issue occurs in win11 Chrome, when I use macos this not occurs.

**Comment by alvhix** [comment]
I'm suffering the same, in W11 chrome the bottom border is not shown and the right side is shown wrong
<img width="489" alt="image" src="https://github.com/giscus/giscus/assets/51875838/73e998a3-bbd2-48bd-89be-3235ae2d7a41">
