### ISSUE TITLE
Private key issues

### ISSUE THREAD

**Issue by Le09** [giscus/giscus#1032]
Sorry about the non-descriptive issue title...

If I enter my repo (Le09/le09.github.io) on the main page, https://giscuss.vercel.app/, I get the following error:
```error	"error:0909006C:PEM routines:get_name:no start line"```
And so I get "Cannot use giscus on this repository. Make sure all of the above criteria has been met."

The 3 criteria have been met; in fact the app is properly running! 
(example https://woolion.art/2022/12/08/WOB.html, although I pushed [a new commit](https://github.com/Le09/le09.github.io/tree/a9299821d58b91f3cc73628db7f06b2e4c7dfb84) to use my own instance since it now works)
However, to complete the script data I had to use the `gh` CLI to get the category id.

Now on the self-hosted version, I got the issue:
```error	"secretOrPrivateKey must be an asymmetric key when using RS256"```
which was really my mistake: because of 
https://github.com/giscus/giscus/blob/d99a6e611685294adfd76220c50b666f9221ab23/.env.example#LL6C28-L6C28
`ENTER-KEY-HERE-WITHOUT-LINE-BREAKS`, I removed line-breaks from the `.pem` file content, which was the problem.
So I would maybe update that file to remove the possibility of confusion, or maybe add a troubleshooting section regarding that.

I got both ways working so this is more to remove friction for other users who might encounter the same issues; I've looked at issue #334, #491 and #921 without finding precise answers.
And much thanks for this project, it looks very nice :-)

**Comment by laymonage** [comment]
Thanks!
