### ISSUE TITLE
Develop tool bug with https://giscus.app/client.js on Chromium brower

### ISSUE THREAD

**Issue by rea1shane** [giscus/giscus#1033]
I find something strange when I use Google Chrome and open develop tool to select html element. Some element can't select，like this (on https://laymonage.com/posts/giscus):

![html-element](https://github.com/giscus/giscus/assets/93363751/eb74122c-374e-47b7-b0f1-7cf7a33fb764)

Same bug on other chromium browser (e.g. Brave). Normal on Safari and Firefox. When I change script scr to local server's js file, everything normal.

So why happened this?

**Comment by laymonage** [comment]
This is a Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1219647
