### ISSUE TITLE
giscus.app refused to connect even with correct giscus.json 

### ISSUE THREAD

**Issue by ak2kay** [giscus/giscus#1079]
my blog site uses hugo as generator. [repo link](https://github.com/ak2kay/blog/tree/port)

I read the doc of giscus.json here: https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#giscusjson, and changed my giscus.json accordingly: [giscus.json](https://github.com/ak2kay/blog/blob/port/giscus.json). But i still got giscus.app refused to connect in my page, you can check it here: [click](https://blog.enceinte.cc/post/2020/extract-sf-pingfang/).

I searched the issues related, i am sure that the window.origin in my site is exactly same as whats inside my giscus.json.  plz help.

**Comment by laymonage** [comment]
giscus looks in the default branch of the repository when loading the `giscus.json` config, which for your repository would be `main`. Your `giscus.json` hasn't been updated on the `main` branch: https://github.com/ak2kay/blog/blob/main/giscus.json
