### ISSUE TITLE
When the page loads, the `gsc-timeline` is added with a `hidden` classname, and the comment content is not displayed

### ISSUE THREAD

**Issue by zkeq** [giscus/giscus#1087]
A hidden classname is added to my page..

see this: https://github.com/giscus/giscus/commit/0c5dbed81436a7754fdf69b93b2e7d0f896bd4f7#r119635865

It gets fired when the page loads.

Recurrence address: [iframe src](https://giscus.app/zh-CN/widget?origin=https%3A%2F%2Fcdn.onmicrosoft.cn%2F&session=&repo=Zkeq%2FCoding&repoId=MDEwOlJlcG9zaXRvcnk0MDc4MDg2MTE%3D&category=General&categoryId=DIC_kwDOFQ4&term=&number=644&strict=0&reactionsEnabled=1&emitMetadata=0&inputPosition=bottom&theme=https%3A%2F%2Fcdn.onmicrosoft.cn%2Fcss%2Fno_comments_light.css&description=%E6%B8%BA%E8%BD%AF+CDN+%E6%98%AF%E4%B8%80%E4%B8%AA%E9%AB%98%E9%80%9F%E3%80%81%E7%AE%80%E5%8D%95%E3%80%81%E5%BC%80%E7%AE%B1%E5%8D%B3%E7%94%A8%E7%9A%84%E5%85%AC%E7%9B%8A+CDN+%E6%9C%8D%E5%8A%A1%E3%80%82%E6%88%91%E4%BB%AC%E5%B8%8C%E6%9C%9B%E8%83%BD%E4%B8%BA%E4%B8%AD%E5%9B%BD%E5%BC%80%E5%8F%91%E8%80%85%E6%8F%90%E4%BE%9B%E4%B8%80%E4%B8%AA%E6%9B%B4%E5%A5%BD%E7%9A%84%E7%BD%91%E7%AB%99%E4%BD%93%E9%AA%8C%EF%BC%8C%E8%AE%A9%E4%B8%AD%E5%9B%BD%E5%BC%80%E5%8F%91%E8%80%85%E4%BD%93%E9%AA%8C%E5%88%B0%E9%80%9F%E5%BA%A6%E4%BC%98%E5%BC%82%E7%9A%84%E5%89%8D%E7%AB%AF%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90%E3%80%82&backLink=https%3A%2F%2Fcdn.onmicrosoft.cn%2F)

the code i used

```tsx
import Giscus from '@giscus/react';

<Giscus
    host='https://giscus.onmicrosoft.cn'
    repo="Zkeq/Coding"
    repoId="MDEwOlJlcG9zaXRvcnk0MDc4MDg2MTE="
    category="General"
    categoryId="DIC_kwDOFQ4"
    mapping="number"
    term="644"
    reactionsEnabled="1"
    emitMetadata="0"
    inputPosition="bottom"
    theme="https://cdn.onmicrosoft.cn/css/no_comments_light.css"
    lang="zh-CN"
  />
```

![image](https://github.com/giscus/giscus/assets/62864752/2b67af7c-8946-462d-958e-cd81d3e0e581)

**Comment by rea1shane** [comment]
Seems a bug. Normal when order in newest.

https://github.com/giscus/giscus/pull/1030#discussion_r1241571301
