### ISSUE TITLE
Received email notification for discussion that was created as a result of my comment...

### ISSUE THREAD

**Issue by da5nsy** [giscus/giscus#1106]
This afternoon I commented on a [blog post](https://jimgrange.github.io/posts/2023-04-02-30DCC-02/), and it looks like this triggered the creation of [the associated conversation page](https://github.com/JimGrange/jimgrange.github.io/discussions/2) _(all good so far)_.

Then, however, I got an email notifying me of this discussion 🤔 
I'm not sure how this works on the backend, but I don't think that this is an intended consequence. I should get emails about _additional_ comments, not about the fact that it was created in the first place...

![image](https://github.com/giscus/giscus/assets/3739866/79ebc415-ba1b-4839-a96f-66a008f646bb)

_I also don't understand how I was subscribed to it before it existed, but that is something that can remain magic to me... ✨_

**Comment by laymonage** [comment]
Thanks, but notifications are all controlled by/via GitHub and have nothing to do with giscus.

**Comment by da5nsy** [comment]
It is weird though that I was notified about a new discussion that was prompted by my action though right? Theoretically, that means that I was subscribed to the discussion before it existed... that seems like smoke to me

**Comment by laymonage** [comment]
It's probably because you own the repository and you're watching it.

**Comment by laymonage** [comment]
It's probably because the discussion creation and comment creation happened so quickly before GitHub's notification system is triggered. GitHub notifications tend to have some delay up to a minute since the event.

**Comment by da5nsy** [comment]
That's a sensible explanation
