### ISSUE TITLE
changes my footer's layout

### ISSUE THREAD

**Issue by ribosomerocker** [giscus/giscus#1111]
Hello. My site is at https://denotation.pages.dev
and the source in https://github.com/ribosomerocker/site/blob/master/output/blog.html
The footer changes between pages that contain giscus and pages that don't.
For an example: 
https://denotation.pages.dev/posts/sample-post
versus
https://denotation.pages.dev

**Comment by laymonage** [comment]
https://github.com/ribosomerocker/site/blob/e066a3a4ab359a16aed70a4eaf6e66443eacde18/web/templates/post.html#L15-L35

Your template is invalid HTML. The `<div id="page">` never gets closed, thus the included `footer.html` will be in that div. This has nothing to do with giscus.
