### ISSUE TITLE
The hidden class is not added to the gsc-timeline element when there are no comments.

### ISSUE THREAD

**Issue by shinyj1991** [giscus/giscus#1145]
![image](https://github.com/giscus/giscus/assets/63823237/36d1a269-deba-4a1a-94f0-716febd2c43c)

I want to know why the hidden class is not added to the gsc-timeline element.

**Comment by shinyj1991** [comment]
It seems to be a phenomenon that occurs before 'Discussions' are automatically generated.
![image](https://github.com/giscus/giscus/assets/63823237/b7906f53-2d95-4490-b3ed-2ca9c214a40e)

**Comment by laymonage** [comment]
Thank you, fixed.

**Comment by shinyj1991** [comment]
@laymonage Thanks!
