### ISSUE TITLE
Is there a way to use vercel storage instead of supabase to cache tokens?

### ISSUE THREAD

**Issue by FloatSheep** [giscus/giscus#1156]
As the title says, use vercel to store the database instead of supabse cache tokens

[Vercel Storage | Vercel Docs](https://vercel.com/docs/storage)

**Comment by laymonage** [comment]
You'll need to implement functions with the same contract as those in https://github.com/giscus/giscus/blob/main/services/supabase/cachedAccessToken.ts, then change the import in https://github.com/giscus/giscus/blob/main/services/github/getAppAccessToken.ts to point to those functions.

I don't think this is something that will be built into the main giscus codebase, as I don't like having to maintain code that is unused by the hosted giscus.app service. As for why I won't use Vercel Storage, they put a rate limit on the API requests and charge you if you go past the limit. Even though this project is sponsored by Vercel, we regularly go past the serverless functions invocation limit every month, so I don't want to add even more cost to them. On the other hand, Supabase allows unlimited API requests on the free tier.
