### ISSUE TITLE
Why do I receive two email reminders when there are new comments?

### ISSUE THREAD

**Issue by YuanJ2003** [giscus/giscus#1170]
Why do I receive two email reminders when there are new comments? How can one from GitHub and one from giscus avoid this situation?
![image](https://github.com/giscus/giscus/assets/105262243/9c0c50b5-862e-4745-bdf1-fbeb3dc5df8f)

**Comment by laymonage** [comment]
The first one is when the discussion is first created by giscus, the second one is when someone leaves the comment. This only happens when the discussion is first created. For the subsequent comments on the same discussion, you'll only receive the notification for each comment.

**Comment by YuanJ2003** [comment]
Thank you!
