### ISSUE TITLE
May I ask how to put the latest comments first?

### ISSUE THREAD

**Issue by YuanJ2003** [giscus/giscus#1171]
May I ask how to put the latest comments first?It seems that they are all sorted from the earliest?I can't change it, I need your help! Thanks!

**Comment by laymonage** [comment]
Click the toggle

<img width="1162" alt="image" src="https://github.com/giscus/giscus/assets/6379424/48dca642-26e3-44fd-ac2a-e05bc84f25f1">

Or add a `giscus.json` to your repository to configure the default
https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#defaultcommentorder

**Comment by YuanJ2003** [comment]
I have solved it, thank you for your help!

**Comment by LaughingZhu** [comment]
can i set anything to change the default sort way as latest
