### ISSUE TITLE
[Bug] Wrong discussion used as comment when search return multiple discussion results

### ISSUE THREAD

**Issue by jiekun** [giscus/giscus#1202]
Step to reproduce:
1. I have some post with similar path and file name:
```
https://jiekun.dev/posts/kubecon-2023/
https://jiekun.dev/posts/kubecon-2023-otel-sampling/
```
2. giscus search with `post/kubecon-2023/` in discussion: [link](https://github.com/jiekun-dev/blog-comment/discussions?discussions_q=posts%2Fkubecon-2023%2F).
3. Github response multiple discussion.
4. giscus choose the wrong one. It mighe because giscus did not exact match the title, but matched the prefix (I did not read the codes, it's my guess)
5. Wrong discussion is displayed as comment in blog post page.

Expected result:
Page https://jiekun.dev/posts/kubecon-2023/ use https://github.com/jiekun-dev/blog-comment/discussions/12 as comment;
Page https://jiekun.dev/posts/kubecon-2023-otel-sampling/ use https://github.com/jiekun-dev/blog-comment/discussions/13 as comment.

**Comment by laymonage** [comment]
It's expected, use the strict matching option if you have such titles.

**Comment by jiekun** [comment]
> It's expected, use the strict matching option if you have such titles.

Thank you, sir. I'm changing the config now. Thanks for your kindly response :0 very appreciated.

**Comment by jiekun** [comment]
Confirm and solved.
