### ISSUE TITLE
404 Not Found，error: "Discussion not found"

### ISSUE THREAD

**Issue by Lzengp** [giscus/giscus#1204]
Version："@giscus/react": "^2.3.0",

Request Address： https://giscus.app/api/discussions?repo=lzengp%2Flw-giscus&term=https%3A%2F%2Flzengp.top%2F&category=Announcements&number=0&strict=true&first=15

Preview： {error: "Discussion not found"}

I saw that other issues have also mentioned this 404 issue, and I have seen the response saying it has been fixed，Has the bug in the React version not been fixed yet?

**Comment by laymonage** [comment]
It’s not a bug, it’s intended if you haven’t created the discussion.

**Comment by Lzengp** [comment]
I just created a new discussion, thank you for your answer
