### ISSUE TITLE
Changing the name of repository will cause previous comments to no longer appear on the site

### ISSUE THREAD

**Issue by Pathsis** [giscus/giscus#1225]
Changing the name of repository will cause previous comments to no longer appear on the site, although they will remain in the repository discussion.

**Comment by laymonage** [comment]
Of course, this is expected... you'll have to update your site's giscus config.

**Comment by Pathsis** [comment]
> Of course, this is expected... you'll have to update your site's giscus config.

Sorry, I now find out that changing the name of the repository does not cause comments to be lost on the site, it only happens when  changing the configuration of mapping.

**Comment by laymonage** [comment]
That is expected too, as the mapping is how giscus finds the correct discussion for each page on your website. If you change the mapping, you'll have to update your discussions as well, giscus will not do it automatically.
