### ISSUE TITLE
403 Response from all giscus comment pull

### ISSUE THREAD

**Issue by jiekun** [giscus/giscus#1249]
It starts with loading:
![image](https://github.com/giscus/giscus/assets/30280396/eda72641-fab6-4136-852b-cc4a7588b2d9)

And then respond with error:
![image](https://github.com/giscus/giscus/assets/30280396/c58bb547-3afd-4834-b2a0-9558bf474805)

I checked the debug tool. But still cannot locate if it's a local network issue or server issue.
![image](https://github.com/giscus/giscus/assets/30280396/598a825f-1768-475d-a028-76469d3ebc8a)

---

My site: https://jiekun.dev/posts/kubecon-na-2023/
My giscus comment repo: https://github.com/jiekun-dev/blog-comment

I think both GitHub and my repo are fine, without any issue opening the discussion page.

This issue is mainly trying to confirm if it happens for other users (or only me). I tried both with/without a VPN proxy, seems nothing different.

**Comment by mmdjiji** [comment]
Same

**Comment by laymonage** [comment]
#1250
