### ISSUE TITLE
Fetch failed

### ISSUE THREAD

**Issue by Canfry** [giscus/giscus#1250]
Since this morning my giscusapp is not loading on my blog. Yesterday was working very well, but today I have the message: An error occured. Fetch failed (see screenshot). I have also went to the blog article where I found how to set up giscus (from Astro weekly page) and the article also have its giscus error at the bottom of the page where normally the comments and reactions should be displayed. Is there a bug ?
<img width="340" alt="Screenshot 2023-11-25 at 09 57 35" src="https://github.com/giscus/giscus/assets/66621302/1971ffd2-3c99-4af7-872c-eee8720e52d5">
You can see here https://elazizi.com/posts/add-comments-section-to-your-astro-blog/?utm_source=astroweekly.beehiiv.com&utm_medium=referral&utm_campaign=astro-weekly-6 that at the bottom of the page when he says that we can leave comments there is the "comments loading" animation and then the error is dispalyed. It seems that not only affecting me. Thanks in advance
My project is an Astro one Astro 3.5 and my repo is Canfry/blog-git-issue

**Comment by SaltedFishesNG** [comment]
I'm having the same problem.

![图片](https://github.com/giscus/giscus/assets/66206988/e9e2d88b-d3f5-483f-a7be-8500d60ca553)

**Comment by laymonage** [comment]
The compute instance I use to cache the tokens became unresponsive this morning for some reason. I've created a new one and rerouted the service, should be OK now. Thank you for the report.

**Comment by qureshiaquib** [comment]
Same for me.

**Comment by mobeicanyue** [comment]
Happend again
