### ISSUE TITLE
How to remove website url in every discussion created

### ISSUE THREAD

**Issue by yvza** [giscus/giscus#1259]
I want to remove this url, it is possible?

Screenshot :
<img width="927" alt="Screenshot 2023-12-13 at 15 07 24" src="https://github.com/giscus/giscus/assets/25668079/89375dd2-ae23-4504-9a60-f44df2e1d6d0">

**Comment by laymonage** [comment]
You can replace it with a non-empty string by adding a

```html
<meta name="giscus:backlink" content="some text here">
```

to your site's `<head>`.

https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#giscusbacklink
