### ISSUE TITLE
Not receiving email notifications for issues migrated to discussions

### ISSUE THREAD

**Issue by thomaslevesque** [giscus/giscus#1262]
A few months ago, I migrated from [Utterances](https://utteranc.es/) (which uses Github issues for comments) to Giscus. As part of the migration process, I converted the issues to discussions.

I just realized that I was not receiving email notifications for new comments in these discussions (at least not always), even though I seem to be subscribed (there's a "unsubscribe" button).

Not sure if it's related, but last week I received several notifications for new discussions created by Giscus for posts that didn't have any comments. The discussions are empty.

I did a test, by asking someone to comment
- on one of the pages for which Giscus created a new discussion: I received the notification
- on one of the pages whose discussion was converted from a Github issue: I didn't receive the notification

I'm not sure if it's a Giscus issue or a Github issue, but it's annoying... Do you know anything about this?

**Comment by thomaslevesque** [comment]
In fact, the problem only seems to happen for the first comment after the issue is converted to a discussion.

**Comment by laymonage** [comment]
Unfortunately anything related to notifications is an issue in GitHub, giscus has no control over it.

See also #1258

**Comment by laymonage** [comment]
That said, I'd suggest reporting this to GitHub, e.g. via https://github.com/orgs/community/discussions under the Issues or Discussions category. That place is a mess though, as some people don't understand that it's supposed to be a place where people give feedback to GitHub about GitHub Discussions, not a general-purpose public discussion forum.

**Comment by thomaslevesque** [comment]
Apparently it's already been reported, but not fixed...
https://github.com/orgs/community/discussions/36377

> That place is a mess though, as some people don't understand that it's supposed to be a place where people give feedback to GitHub about GitHub Discussions, not a general-purpose public discussion forum.

Ironic that even though Github offers an issue tracker, there's no clearly defined bug tracker for Github itself...
