### ISSUE TITLE
Change the hover color of next button

### ISSUE THREAD

**Issue by wakhoo** [giscus/giscus#1265]
<img width="523" alt="스크린샷 2023-12-23 16 06 40" src="https://github.com/giscus/giscus/assets/40779092/a88514bf-988c-4fb3-bd73-3eeece3ec83d">
how can I change the hover color of next button? I search for it but it's too hard to find it..can somebody help me?

**Comment by laymonage** [comment]
Sorry but I have no idea what you’re talking about, it doesn’t look related to this project at all.
