### ISSUE TITLE
404 Discussion not found

### ISSUE THREAD

**Issue by zzsqwq** [giscus/giscus#1268]
Hello, recently I found that when giscus try to pull the discussion through API, it return "404 Discussion not found". However, the discussion in my repo is open normally. In the past, it could also work normally. May I ask where the problem might be? Thanks!

My repo discussion link：https://github.com/zzsqwq/hugo-blog-comment/discussions?discussions_q=

giscus query data api link：https://giscus.app/api/discussions?repo=zzsqwq/hugo-blog-comment&term=posts/summary-2022/&category=Announcements&number=0&strict=false&first=15 

![CleanShot 2023-12-27 at 16 57 59@2x](https://github.com/giscus/giscus/assets/57089406/b1f036aa-2e90-433b-9ff8-c3edb094e768)

**Comment by laymonage** [comment]
I don't know, looks like there's something wrong with your repository on GitHub's side and has nothing to do with giscus. Clicking the Discussions tab on your repo even returns no results: https://github.com/zzsqwq/hugo-blog-comment/discussions

Looks like if you put anything in the search query, it doesn't work. So maybe there's an issue with the search index. Try adding stuff on your repo, perhaps that would trigger a reindex on GitHub's server.

**Comment by huykon** [comment]
I have same issue

**Comment by zzsqwq** [comment]
> I have same issue

@huykon  I posted a [related thread](https://github.com/orgs/community/discussions/83995) on the Github Community, but no one replied. However, I found a workaround, which is to first close the problematic discussion and then reopen it. Everything will return to normal. Please note that this will send notification emails to those subscribed to the discussion. Hope this helps :)

**Comment by yqchilde** [comment]
@zzsqwq 你有修改过项目名吗？如果修改过的话，看看代码配置里的仓库是否还是原来的

**Comment by zzsqwq** [comment]
> @zzsqwq 你有修改过项目名吗？如果修改过的话，看看代码配置里的仓库是否还是原来的

没有，应该就是单纯 GitHub 的 bug，把所有的 Discussion 关闭重新打开就正常了。

**Comment by yqchilde** [comment]
> > @zzsqwq 你有修改过项目名吗？如果修改过的话，看看代码配置里的仓库是否还是原来的
> 
> 没有，应该就是单纯 GitHub 的 bug，把所有的 Discussion 关闭重新打开就正常了。

好吧，我刚遇到了所以搜到了这个issue，结果发现是我rename过

**Comment by Arugin** [comment]
I have the same issue. It loads existing discussions but for some reason couldn't create a new one. What should I do?

**Comment by Arugin** [comment]
Here is a site: https://blog.unbegames.com/en/posts/january-developer-update/
Here is a discussions: https://github.com/unbeGames/unbegames.github.io/discussions

**Comment by Arugin** [comment]
![image](https://github.com/giscus/giscus/assets/833064/a7baae28-8122-44ca-b59c-4e9bed3c32ef)

**Comment by Zamoca42** [comment]
I had the same issue, and the 404 error disappeared when I changed the Discussion Format to Announcement in the Category settings. Check the format connected to giscus.

<img width="746" alt="category" src="https://github.com/giscus/giscus/assets/96982072/2d491f86-3bb8-45b3-a771-b3f6b727f907">

**Comment by TheDarkStarJack** [comment]
> > @zzsqwq 你有修改过项目名吗？如果修改过的话，看看代码配置里的仓库是否还是原来的
> 
> 没有，应该就是单纯 GitHub 的 bug，把所有的 Discussion 关闭重新打开就正常了。

尝试将 Discussion  重新打开也不行，最后尝试自己手动在仓库的 Discussion 添加了一条记录之后可以正常使用了😒
