### ISSUE TITLE
giscus rejects all/any repos I select despite meeting all conditions

### ISSUE THREAD

**Issue by tholonia** [giscus/giscus#1272]
I am trying to add Giscus to my repo, and when configuring Giscus (https://giscus.app/) it asks:

```
Choose the repository giscus will connect to. Make sure that:

The repository is [public](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/setting-repository-visibility#making-a-repository-public), otherwise visitors will not be able to view the discussion.

The [giscus](https://github.com/apps/giscus) app is installed, otherwise visitors will not be able to comment and react.

The Discussions feature is turned on by [enabling it for your repository](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/enabling-or-disabling-github-discussions-for-a-repository).

```
All 3 conditions ARE satisfied, yet when I enter the `username/reponame` it always responds with:

`Cannot use giscus on this repository. Make sure all of the above criteria have been met.`

Discussions have been enabled for the repos, I have created discussion-only repos as well, with the same error message.  

What am I missing?

**Comment by supleed2** [comment]
It's probably to do with #1269

**Comment by laymonage** [comment]
Yes it is
