### ISSUE TITLE
An error occurred: fetch failed

### ISSUE THREAD

**Issue by 1kevinson** [giscus/giscus#1275]
Unable to load Giscus comment component from any site that uses Giscus

https://os.phil-opp.com/testing/#comments

https://1kevinson.com/write-a-brag-document-and-get-your-work-recognized/#__next

https://laymonage.com/posts/giscus/#__next

## Screenshot

![CleanShot 2023-12-31 at 14 35 22@2x](https://github.com/giscus/giscus/assets/59510116/6145ba1a-6ae2-4e46-ad78-cc0cda675238)

**Comment by laymonage** [comment]
#1269
