### ISSUE TITLE
 An error occurred. Error message: "fetch failed".

### ISSUE THREAD

**Issue by kisnows** [giscus/giscus#1276]
I got an error when use giscus:
<img width="1025" alt="image" src="https://github.com/giscus/giscus/assets/9394000/cb1acf49-b4af-42db-be4b-a5c4e89ce3e3">

My repo is https://github.com/kisnows/blog-comment , already open the discussions function,and i install ths giscus app and open the access for my repo
<img width="577" alt="image" src="https://github.com/giscus/giscus/assets/9394000/1c7657b5-ea91-4419-869f-38a69a113e2d">

and i success post comment in my local dev env.
<img width="646" alt="image" src="https://github.com/giscus/giscus/assets/9394000/21579a7a-0917-4459-8088-64609cdaeb49">

But when i deploy my website online , and then every thing is not right , i con't find the soultion.

Only can't see a request `https://giscus.app/api/discussions?repo=kisnows%2Fblog-comment&term=2014%2F12%2F11%2Flearning-note-1&category=Announcements&number=0&strict=false&last=15` with a  403 res code, this is the req detail:
```js
fetch("https://giscus.app/api/discussions?repo=kisnows%2Fblog-comment&term=2014%2F12%2F11%2Flearning-note-1&category=Announcements&number=0&strict=false&last=15", {
  "headers": {
    "accept": "*/*",
    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
    "cache-control": "no-cache",
    "pragma": "no-cache",
    "sec-ch-ua": "\"Not_A Brand\";v=\"8\", \"Chromium\";v=\"120\", \"Google Chrome\";v=\"120\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin"
  },
  "referrer": "https://giscus.app/",
  "referrerPolicy": "strict-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "omit"
});
```

This is my website url: https://blog.kisnows.com .

**Comment by laymonage** [comment]
#1269
