### ISSUE TITLE
Sign in with Github not working

### ISSUE THREAD

**Issue by vickyRathee** [giscus/giscus#1280]
How to investigate login with Sign with github not working. 
I setup everything properly but when I am logged in, it still show "Sign in with Github"

Example link - 
https://agenty.com/docs/how-to-scrape-all-product-color-variants/173

**Comment by laymonage** [comment]
Your website seems to redirect and remove any query parameters added to the link, e.g. https://agenty.com/docs/how-to-scrape-all-product-color-variants/173?test=abcd will redirect to https://agenty.com/docs/how-to-scrape-all-product-color-variants/173, losing the `test=abcd`.

giscus passes a query param when redirecting to your website to continue the authentication process, but your website removes it before giscus has a chance to use it.

**Comment by vickyRathee** [comment]
@laymonage Awesome, thanks for your help. I will fix it on website level.
