### ISSUE TITLE
Is there a way to position giscus on a page if I can only add JS to the header?

### ISSUE THREAD

**Issue by jlxq0** [giscus/giscus#1306]
I have a website on http://fireside.fm, which is basically a hosted CMS. I can't use much custom code. Pages get generated for me.

I can however
- add arbitrary JS either in the <head>
- add arbitrary JS right before </body>
- add content to the page (e.g. a href with PLACEHOLDER as a destination).

Is there a way to have the giscus code plus some custom code (which code?) in either the head or before the body ends, and when the page loads, instead of having giscus show up right where I put the giscus JS, it will show up instead of PLACEHOLDER?

**Comment by laymonage** [comment]
Yes, add an element with a `giscus` class and it’ll be placed there.

**Comment by jlxq0** [comment]
Hmmm ... My approach was placing this in the header:


```js
<script>
window.addEventListener('load', function () {
  var node_to_replace = document.querySelector('li a[title="PLACEHOLDER"]').parentElement;
  var giscus_div = document.createElement('div');
  giscus_div.className="giscus";
  node_to_replace.replaceWith(giscus_div);
})
</script>
```

Is that a valid approach?

It is working as in: it is replacing that PLACEHOLDER link with a div with the class `giscus` – however giscus is still loading at the end of the page. Maybe some kind of "race condition"?

(I should add that I cannot just add any random content to the page, and thus can't just add a div with a specific class myself. The only thing I can add in that position is links and the only thing I can influence of the links is the title, the href and the text between the a-tags.)

**Comment by laymonage** [comment]
Yeah the giscus script tag loads immediately instead of being in a `load` event listener so your script probably gets executed after giscus loads. Either make it run immediately (and put it before the giscus script tag), or add the giscus script tag dynamically: https://github.com/giscus/giscus/issues/336#issuecomment-1009551934 (you can probably just avoid making the `div.giscus` element and put the dynamically created script right where the placeholder is).

**Comment by jlxq0** [comment]
Sorry for not getting back earlier, @laymonage.

I'm still not sure this is the most elegant solution, but it works, as you can see on https://www.sleepless.sg/1 – and that's what counts for me. 👍 

```js
<script>
  window.addEventListener('load', function () {
    var node_to_replace = document.querySelector('li a[title="PLACEHOLDER"]').parentElement;
    var giscus_div = document.createElement('div');
    giscus_div.className="giscus";
    node_to_replace.replaceWith(giscus_div);

    let giscusAttributes = {
      "src": "https://giscus.app/client.js",
      "data-repo": "xxx",
      "data-repo-id": "xxx",
      "data-category": "Website Comments",
      "data-category-id": "xxx",
      "data-mapping": "pathname",
      "data-reactions-enabled": "1",
      "data-emit-metadata": "0",
      "data-theme": light,
      "data-lang": "en",
      "crossorigin": "anonymous",
      "async": "",
    };

    let giscusScript = document.createElement("script");
    Object.entries(giscusAttributes).forEach(([key, value]) => giscusScript.setAttribute(key, value));
    document.body.appendChild(giscusScript);
  })
</script>
```

Thank you so much; I appreciate the help a lot!
