### ISSUE TITLE
Prevent Other Repos from Creating Discussions

### ISSUE THREAD

**Issue by timothystewart6** [giscus/giscus#1311]
I have found that anyone can spam your discussion board if they use the wrong repo ID when configuring their instance of giscus.   

Is there a way to block this or have more granular control over which repo the bot is authorized to post in?

I ask because some people copy a template that I have that is public and end up using my repo ID and then all of their test comments appear in my discussion.

I think this might be related to this page and probably the reason it was set up.
https://github.com/orgs/giscus/discussions/1298

**Comment by laymonage** [comment]
https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#origins

**Comment by timothystewart6** [comment]
Thank you so much!  Sorry I didn't see that!
