### ISSUE TITLE
is it down? can't load comments anymore.  even on the offical home page.

### ISSUE THREAD

**Issue by yuqianyi1001** [giscus/giscus#1319]
An error occurred: fetch failed 

see here: https://giscus.app

![image](https://github.com/giscus/giscus/assets/52897651/e7a9ef04-1a4d-44af-98ed-7965723cfc86)

the show case page has error too.

https://laymonage.com/posts/giscus

![image](https://github.com/giscus/giscus/assets/52897651/4b8eefa0-eb91-4651-9603-88a6af9de17b)

**Comment by laymonage** [comment]
Yeah, fixed now.

**Comment by trevortylerlee** [comment]
I'm getting errors as well now. The giscus.app website's comments are also not working.

When I try entering my repo it fails with error "Cannot use giscus on this repository. Make sure all of the above criteria has been met".
