### ISSUE TITLE
In multilingual website, unable to distinguish between different language versions of a page

### ISSUE THREAD

**Issue by Pathsis** [giscus/giscus#1321]
If any language version generates a comment, all language versions generate the same comment.

Please visit [https://pathos.page/blog/long-live-rss](https://pathos.page/blog/long-live-rss) to test this, it also has a Chinese version.

The site is built with next.js.

**Comment by laymonage** [comment]
There's the `strict` mode for this purpose: https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#data-strict
