### ISSUE TITLE
ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by sonicoder86** [giscus/giscus#1322]
I'm trying to use the Gisqus React component based on this starter template https://github.com/timlrx/tailwind-nextjs-starter-blog

If I add the environment variables for Gisqus after installing the app and enabling Discussions for the repository, the component fails to load with the error message:

`ReferenceError: exports is not defined`

Changing the `compilerOptions` in my `tsconfig.json` doesn't help.

**Comment by laymonage** [comment]
https://github.com/giscus/giscus-component/issues/1976
