### ISSUE TITLE
URI_TOO_LONG error

### ISSUE THREAD

**Issue by hxglife** [giscus/giscus#1340]
Hello giscus team,

I'm using giscus on my blog, which is built with Hugo on Cloudflare Pages.

On most pages, giscus works fine. However, some pages report URI TOO LONG error. I searched for related information and this error bothered me because only a few pages reported errors and other pages are normal.

the error pages:
- https://hxg.life/200606/
- https://hxg.life/170805/
- https://hxg.life/160101/

the normal pages:
rest of my posts

Can anyone help?

**Comment by hxglife** [comment]
update 
I carefully checked the relevant code. This error was caused by the theme and has been resolved.

**Comment by gexiaoxiao7** [comment]
> update
> I carefully checked the relevant code. This error was caused by the theme and has been resolved.

I have same problem, and I do not understand what's the matter with the theme, will you provide more details? thanks!

**Comment by gexiaoxiao7** [comment]
Never mind, I solved the problem. It is caused by string exceeding limit, most likely because the "description" field. I added below codes and it works well.

`<!-- meta name="description" -->`

**Comment by gexiaoxiao7** [comment]
Never mind, I solved the problem. It is caused by string exceeding limit, most likely because the "description" field. I added below codes in the begining of my markdown content and it works well.

**Comment by gexiaoxiao7** [comment]
Never mind, I solved the problem. It is caused by string exceeding limit, most likely because the "description" field. I added below codes in the begining of my markdown content and it works well.

`<!-- meta name="description" -->`

**Comment by Sciroccogti** [comment]
> update I carefully checked the relevant code. This error was caused by the theme and has been resolved.

I also ran into the same issue, however I have no idea which code should I look into. Would you please show me some clue?

**Comment by 01joy** [comment]
@hxglife @Marshall-Ge I am facing the same problem, and using the [PaperMod ](https://github.com/adityatelange/hugo-PaperMod/) theme. Could you give me some hints on how to resolve the problem, thank you.

**Comment by 01joy** [comment]
I finally resolve the problem.

The giscus URI contains the description information of the post. When you do not set the description, hugo will use the post content as the description. As a result, if your post is very long, the description will be very long too, which then results in the `URI_TOO_LONG` error.

The solution is very easy, just manually set a short `description` in your `Front matter` area.

For more information, please see my bolg: https://bitjoy.net/posts/2025-11-09-resolve-the-uri-too-long-error-of-giscus-in-hugo/
