### ISSUE TITLE
Dynamic theme in Vitepress

### ISSUE THREAD

**Issue by MikeCZ23** [giscus/giscus#1360]
### Discussed in https://github.com/orgs/giscus/discussions/1359

<div type='discussions-op-text'>

<sup>Originally posted by **MikeCZ23** April 17, 2024</sup>
Hello, is dynamic theme changing available? Because, I want this to change the theme automatically, according to the website.
vitepress
[my repo](https://github.com/MikeCZ23/mikecz23.github.io/blob/main/.vitepress/theme/components/gisqus.vue)</div>

**Comment by laymonage** [comment]
There are many issues around this topic already, e.g. #1200 and #336. TLDR: giscus already has the mechanisms to let you do it, but expect to write your own code that tells giscus to change the theme, as it has no idea how the theming of your website works.
