### ISSUE TITLE
{"error":"secretOrPrivateKey must be an asymmetric key when using RS256"}

### ISSUE THREAD

**Issue by LoongmaSpirit** [giscus/giscus#1378]
部署在 Netlify 平台时，访问 github app 数据时 403，并提示：`must be an asymmetric key when using RS256`。

配置如下：

![image](https://github.com/giscus/giscus/assets/162437080/55c70601-f3d1-49f2-b9ed-6f2f465da1c8)

在每个换行出，加 `\n` 与不加 `\n` 等各种方法都试过了，结果一样

**Comment by LoongmaSpirit** [comment]
经测试，github rsa 私钥必须放在工程的 .env 文件中才会生效，通过 Netlify 的 Env 配置估计会被修改字符，导致校验失败。

**Comment by Ramos-x** [comment]
真绷不住了，这个问题折腾了一下午

**Comment by laymonage** [comment]
It's a Netlify limitation, it does not support multiline environment variables: https://answers.netlify.com/t/support-guide-using-an-ssh-key-via-environment-variable-during-build/2457

You can probably fix this with a string replacement here: https://github.com/giscus/giscus/blob/d1c6705002527050074ffd697393bb25c8f65961/lib/variables.ts#L7

with something like

```ts
process.env.GITHUB_PRIVATE_KEY.replace(/\\n/gm, "\n")
```

See https://answers.netlify.com/t/long-environment-variable-with-line-breaks-n/8514/6

P.s. next time, if you can't write in English, I recommend putting it through Google Translate or something first. I don't speak Chinese, so I could've given a faster response if I didn't have to translate your comments myself.

**Comment by LoongmaSpirit** [comment]
> 真绷不住了，这个问题折腾了一下午

hahaha, 解决了就好

**Comment by LoongmaSpirit** [comment]
> It's a Netlify limitation, it does not support multiline environment variables: https://answers.netlify.com/t/support-guide-using-an-ssh-key-via-environment-variable-during-build/2457
> 
> You can probably fix this with a string replacement here:
> 
> https://github.com/giscus/giscus/blob/d1c6705002527050074ffd697393bb25c8f65961/lib/variables.ts#L7
> 
> with something like
> 
> ```ts
> process.env.GITHUB_PRIVATE_KEY.replace(/\\n/gm, "\n")
> ```
> 
> See https://answers.netlify.com/t/long-environment-variable-with-line-breaks-n/8514/6
> 
> P.s. next time, if you can't write in English, I recommend putting it through Google Translate or something first. I don't speak Chinese, so I could've given a faster response if I didn't have to translate your comments myself.

Haha, I originally thought the developer was Chinese, so I didn't translate it. now I understand.
