### ISSUE TITLE
Giscus loads the comment entry and that puts comments in but shows cannot load Discus error

### ISSUE THREAD

**Issue by steowens** [giscus/giscus#1379]
If you go to https://electsteveowens.org, you can see that the giscus.app/client.js is embedded per instructions but it shows a fails to load Discuss error and I don't know what to do about that, especially since were using Giscuss not Discuss.

**Comment by laymonage** [comment]
This has nothing to do with giscus, you have leftover Disqus configuration in your website's code. It doesn't seem to be open source so I can't help you fix it.
