### ISSUE TITLE
"fetch failed" problem recurs

### ISSUE THREAD

**Issue by Oh-noodles** [giscus/giscus#1382]
![image](https://github.com/giscus/giscus/assets/16266766/9d9eed21-d640-4db5-815d-d6df5355bdb7)

**Comment by laymonage** [comment]
It's working for me now. Not sure what happened.

**Comment by tautvydasversockas** [comment]
I’ve just tested (right this minute) and it doesn’t work for me. I’ve tried the following pages with giscus enabled:

https://thehonestcoder.com/ddd-ef-core-8/
https://andrewlock.net/migrating-comments-from-dsqus-to-giscus/

Both of these websites return “fetch failed”.
