### ISSUE TITLE
An error occurred. Error message: "fetch failed". Please consider reporting this error at

### ISSUE THREAD

**Issue by Justice996** [giscus/giscus#1383]
An error occurred. Error message: "fetch failed". Please consider reporting this error at

**Comment by laymonage** [comment]
Yes, I'm aware of this issue affecting several installations of giscus. It doesn't seem to affect https://giscus.app or my own website, though, so I'm not sure what the issue is. I'm at work at the moment so I can't fix this until later tonight.

**Comment by Justice996** [comment]
> Same here, I think it's a general issue at the moment.

ok thanks,I thought it was my network problem, but it seems it isn't

**Comment by yinan-c** [comment]
> It doesn't seem to affect https://giscus.app or my own website, though

Comments in https://giscus.app seem to be down as well.

**Comment by laymonage** [comment]
Ah, just realised that I was logged in to giscus.app and my website so I didn't see the issue. Yeah the cache server seems to have gone offline for some reason. I've restarted, now it should work again. Thanks for reporting!
