### ISSUE TITLE
Set font for giscus

### ISSUE THREAD

**Issue by Thecode764** [giscus/giscus#1386]
Hello.

i speak persian too. My website language is persian. i use persian version of giscus

how to set a persian font for giscus?

**Comment by laymonage** [comment]
@KagamiChan yep, thanks!

**Comment by ricolxwz** [comment]
It's so difficult to change the font, even if I served data-theme with my own cdn and modified css file, nothing changed.

**Comment by laymonage** [comment]
PRs are welcome.
