### ISSUE TITLE
How to add duplicate Giscus Widget on a page?

### ISSUE THREAD

**Issue by sohang3112** [giscus/giscus#1392]
In [my blog](https://sohang3112.github.io/blood-sweat-and-pixels-book-review/), I have added Giscus likes & comments widget `<iframe>` at the bottom of the page. How can I duplicate it at the top also, so that like & comment buttons show at both the start & end of the blog post? For example, Medium shows these like & comment bottons at the start & end of blog posts:

![Medium like & comment buttons](https://github.com/giscus/giscus/assets/31966963/17dbff57-6c17-43d1-a957-ae6cf47de266)

**Comment by laymonage** [comment]
You can use the [web component](https://github.com/giscus/giscus-component) to render multiple instances of the widget on the same page. I don't recommend it though, especially if you're not self-hosting it.
