### ISSUE TITLE
I was trying to add giscus functionality by hosting it on Vercel

### ISSUE THREAD

**Issue by Samdasoo1076** [giscus/giscus#1396]
![image](https://github.com/giscus/giscus/assets/84221209/1a40ec6e-082c-40c1-b0ed-c0bf76235b37)

I've followed all of these instructions, but I'm getting this error Eror
: 
`Giscus Isnote Installed on Teeth Repository`

![image](https://github.com/giscus/giscus/assets/84221209/11a697b2-255b-442e-b8a5-23c2363c1ebb)

![image](https://github.com/giscus/giscus/assets/84221209/1f561081-227d-46f3-8540-6018dc40a761)

![image](https://github.com/giscus/giscus/assets/84221209/17d9eac5-a197-41bf-80d1-705e97e29bf4)

# I don't know how to solve this problem

**Comment by laymonage** [comment]
You're inserting those values in `.env.example`, which is just an example file. You should put it directly on Vercel: https://vercel.com/docs/projects/environment-variables

Also, this is not directly related to giscus, and you've already opened https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/933 so I'll close this.
