### ISSUE TITLE
能不能添加功能栏

### ISSUE THREAD

**Issue by JoyBoy521** [giscus/giscus#1398]
添加一下功能栏就像github本身的评论功能一样，
比如，giscus评论没有上传图片的按钮，
![Screenshot_2024-06-13-02-09-15-435_com microsoft emmx-edit](https://github.com/giscus/giscus/assets/154486203/0c8a35e7-8c11-4935-a34c-b2ba9e6b848c)

**Comment by JoyBoy521** [comment]
最重要的是弄一个图片上传功能，这个功能是不是很难实现

**Comment by laymonage** [comment]
#197
