### ISSUE TITLE
How to get data-repo-id and data-category-id?

### ISSUE THREAD

**Issue by luzhixing12345** [giscus/giscus#1402]
for now I just fill the blank and copy it from  https://giscus.app/, but I want to add giscus for all my repos , is it possible to automatically get `data-repo-id` and  `data-category-id` by repo name and category name?

> I have tried to ignore it but could not send comments

**Comment by laymonage** [comment]
You can use [GitHub's GraphQL explorer](https://docs.github.com/en/graphql/overview/explorer) to get the IDs in batches, e.g.

```graphql
query {
  zood: repository(owner: "luzhixing12345", name: "zood") {
    id,
    discussionCategory(slug: "q-a") {
      id,
      name
    }
  },
  
  klinux: repository(owner: "luzhixing12345", name: "klinux") {
    id,
    discussionCategory(slug: "show-and-tell") {
      id,
      name
    }
  },
}
```
