### ISSUE TITLE
[Featrue Request] Use md5 of pathname as the title of dicussion. 

### ISSUE THREAD

**Issue by louiesun** [giscus/giscus#1407]
I've tested that when the title is too long, it is hard to add a comment. (As I know, in gitalk, issue title can't be longer than 50 ASCIIs, so too long may cause problem).
If we use md5, it will be always 32 ASCIIS. (or 16)
I used to try `specified` but failed to use a dynamic string as the `term` with vue. (I am not good at vue, but my blog based on vitepress and it origial supports vue). 
It is very easy to code. 
On npm, we have [ts-md5](https://www.npmjs.com/package/ts-md5).
Just modify `location.pathname` to `Md5.HashStr(location.pathname)`! 
Or a new alternative of ``mapping`?

**Comment by laymonage** [comment]
There's already the "strict" option which uses SHA1 to hash the term that is then embedded in the discussion body, and it works with any mapping (`pathname`, `title`, etc.).

<img width="727" alt="image" src="https://github.com/giscus/giscus/assets/6379424/49be7767-5b07-4a9f-8df9-3454132fff13">

**Comment by louiesun** [comment]
I am mainly worried with the too long path.
You know, hash is developed becaus the origin file is too large to campare.
