### ISSUE TITLE
[Error Report] Fetch Failed Error

### ISSUE THREAD

**Issue by IT-HONGREAT** [giscus/giscus#1417]
I encountered a "fetch failed" error.

The error response is: {"error":"fetch failed"}.

On the https://giscus.app/ page, the same "fetch failed" error is displayed at the bottom, so I think it might be a server issue.

Based on what I saw in the developer tab, I'm registering this issue.

[giscus] An error occurred. Error message: "fetch failed". Please consider reporting this error at https://github.com/giscus/giscus/issues/new.

![image](https://github.com/giscus/giscus/assets/80932397/cb4b3ee1-07e9-41e4-9996-dfc020d7b6fe)

Thank you for your efforts.

**Comment by heomne** [comment]
i have a same issue

**Comment by laymonage** [comment]
Fixed
