### ISSUE TITLE
deploy to netlify has console warning

### ISSUE THREAD

**Issue by skyline523** [giscus/giscus#1432]
Warnings are always output in console. It seems to be a problem with script preloading. I don't know hot to clean the warning
![image](https://github.com/user-attachments/assets/7844d440-8c0f-4641-b55b-c5c7b1b21ed8)

this is my giscus component`(@giscus/vue)` config

```vue
<Giscus
      v-if="hasGiscus"
      repo="skyline523/leet.me"
      repo-id="R_kgDOMV5mBg"
      category="Announcements"
      category-id="DIC_kwDOMV5mBs4ChjO0"
      mapping="og:title"
      term="Welcome to leet.me"
      strict="1"
      reactions-enabled="1"
      emit-metadata="0"
      input-position="top"
      :theme="isDark ? 'transparent_dark' : 'light'"
      lang="zh-CN"
/>
```

**Comment by laymonage** [comment]
That comes from your website and how it preloads fonts, not giscus.
