### ISSUE TITLE
giscus.app refused to connect

### ISSUE THREAD

**Issue by nijobair** [giscus/giscus#1449]
I am integrating giscus for commenting on my website made with GitHub pages. I did everything correctly yet I keep getting this message:
[giscus.app](http://giscus.app/) refused to connect.

On the Chrome console, it shows:

`Refused to frame 'https://giscus.app/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".`

<img width="347" alt="image" src="https://github.com/user-attachments/assets/e3024871-0210-412a-96c0-09589a054c6b">

How can I solve this problem? Thanks in advance 💐.

**Comment by laymonage** [comment]
https://github.com/nijobair/nijobair.github.io/commit/0fda66b84dba6255d452b539bc005b6ac0eb0b2a#diff-88e83e5d0edb4286d0e35534fa9f49405a4ef6724137b468772a31183cb43a3fR54

```diff
-data-lang=" en"
+data-lang="en"
```

**Comment by nijobair** [comment]
Thank you 💐. It's working now.

One question: Is there a light version of the "transparent_dark" theme? "NoBorder Light" is close to it but not the same.

**Comment by nijobair** [comment]
Unfortunately, I have no idea how these things work.

I have applied the "transparent_light" theme to my website (not ready). You can have a look at it here: [transparent_light](https://nijobair.github.io/posts/dax/powerbi/25-days-of-dax-fridays-challenge-ed1-northwind-company/). You can have a look at it.
