### ISSUE TITLE
An error occurred: API rate limit exceeded for giscus/giscus - After Signing In

### ISSUE THREAD

**Issue by pourmand1376** [giscus/giscus#1524]
Hi. 

Today. I understood that the `giscus` system doesn't work after we click sign in. 

![CleanShot 2024-10-05 at 11 20 28@2x](https://github.com/user-attachments/assets/865040d2-d721-42cf-8efe-e750650897c3)

This is the official giscus website picture after I hit sign in. I also have this problem on two of my websites.

Note that this doesn't happen `always`. But in the last couple of days, I've been seeing this a lot.

**Comment by pourmand1376** [comment]
I tested this a lot and I came into conclusion that my account is limited due to high number of API Requests. 

I don't know how to resolve it. But I will consider it more.

**Comment by laymonage** [comment]
Thanks, but well, GitHub does have a rate limit on their API. We definitely can improve the widget to work more efficiently, but since this isn't something that's happening regularly I'll close this.
