### ISSUE TITLE
Comments are always on a page instead of just at the bottom of the post.

### ISSUE THREAD

**Issue by tdavetech** [giscus/giscus#1541]
I added giscus to my hugo site and the comments section just kind of stays overlayed on top of my post instead of only being at the bottom like this: 
![image](https://github.com/user-attachments/assets/8863df4d-3f10-4459-9c5d-d30a8891af6f)

**Comment by laymonage** [comment]
It's something to do with your site's template, make sure you place the script tag where you want the comments to be, or use an element with a `giscus` class on it so the script knows to put it there.

I cannot help you without a link to your website and the source code.
