### ISSUE TITLE
Add support for mathematical expressions

### ISSUE THREAD

**Issue by IamSreeman** [giscus/giscus#165]
Can [this plugin](https://chrome.google.com/webstore/detail/mathjax-plugin-for-github/ioemnmodlmafdkllaclgeombjnmnbima) be supported? It can render any LaTeX equations within the GitHub markdown using MathJax. It is working perfectly fine when I open comments in the discussions. But giscus is showing LaTeX code without rendering. Or should I open an issue in the repo of that plugin if this can only be done by them?
Repo of that plugin: https://github.com/orsharir/github-mathjax

**Comment by laymonage** [comment]
Hey, thanks for the suggestion. I do agree that having support for LaTeX equations would be nice. Unfortunately, I am not a fan of modifying the comments' contents before they are displayed to the users. In addition, I try to match the interface as closely as possible with GitHub's. Your best bet would be to ask them to support giscus, which I think should be possible, but I don't know how hard of a task it would be.

A possible workaround would be to use [this trick](https://gist.github.com/a-rodin/fef3f543412d6e1ec5b6cf55bf197d7b), which would work on GitHub and giscus without resorting to a browser extension.

Related: https://github.com/github/markup/issues/1294 and https://github.com/github/markup/issues/897

**Comment by IamSreeman** [comment]
@laymonage GitHub now [supports](https://github.blog/changelog/2022-05-19-render-mathematical-expressions-in-markdown/) LaTeX. I tried testing giscus with it. It is rendering properly on the discussions page, but it is not rendering in the giscus script. Should I open a new issue?

**Comment by IamSreeman** [comment]
<img src="https://media3.giphy.com/media/13mfssn73An6De/giphy.gif"/>

**Comment by laymonage** [comment]
Hey, thanks for the reminder! We use [GitHub's Markdown Renderer API](https://docs.github.com/en/rest/markdown) and it seems it hasn't been updated to support $\LaTeX$. I've sent a feedback to them [here](https://github.com/github/feedback/discussions/16945).

**Comment by laymonage** [comment]
@IamSreeman It's now supported! Turns out I just had to add a small shim on the client-side to render the custom element. See #548 :)

**Comment by IamSreeman** [comment]
@laymonage cool and thanks.

**Comment by IamSreeman** [comment]
@xeonmc Your test comments are rendering normally in my device. Problem is probably due to your browser or some extension.

![Screenshot_2022-07-29-16-15-43-46_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/62174391/181743418-6866d446-6fe5-4ee7-b1c9-34bd3df57d7b.jpg)

**Comment by IamSreeman** [comment]
@xeonmc if the problem was with the browser or extensions then even for https://giscus.app/ the rendering shouldn't work. So, I don't know what the actual problem is.

**Comment by laymonage** [comment]
Ah yes, that could be because the mathjax code is loaded from a CDN.

https://github.com/giscus/giscus/blob/73be8f4e949b3f6766f8f0ccbe2b5bcfc72abe1f/lib/vendor/math-renderer-element.ts#L61

I can try self-hosting it, maybe that would fix the issue.

**Comment by laymonage** [comment]
@xeonmc I've self-hosted the libraries in #637, could you test again? Thanks!

**Comment by laymonage** [comment]
Okay I think I've fixed it, it was because the code was accessing `localStorage` and Firefox blocks that if you enable strict protection.
