### ISSUE TITLE
Self-Host issues with logged in users

### ISSUE THREAD

**Issue by patgarz** [giscus/giscus#191]
Hey there - I've been grinding on this issue for a little while now and am hoping I've just done something dumb and you have an easy fix for me.

I'm attempting to run a self-hosted version of giscus at [giscus.pgarz.com](https://giscus.pgarz.com). In the test comment area below, it appears to work fine for not-logged-in users, but once I auth, nothing shows up. Investigating in the web console (Edge) shows the following error: 
```
[giscus] An error occurred. Error message: "Unable to retrieve token.". Please consider reporting this error at https://github.com/giscus/giscus/issues/new.
```

I'm able to auth successfully at [giscus.app](https://giscus.app) so I must be missing something.

I've pushed my changes to [patgarz/giscus](https://github.com/patgarz/giscus/commit/552cb274ec548c585a0b655f8ad095244fb237a7) in case you want to take a look.

Thanks! Love the project.

**Comment by laymonage** [comment]
Hey, I'm guessing there's a misconfiguration in your environment variables. Make sure you have the correct values for the following variables:

- `GITHUB_APP_ID`
- `GITHUB_CLIENT_ID`
- `GITHUB_CLIENT_SECRET`
- `GITHUB_PRIVATE_KEY`
- `ENCRYPTION_PASSWORD`

The most likely would be the private key. You can try running the app locally for easier debugging.

**Comment by patgarz** [comment]
Got it working - I had fixed GITHUB_PRIVATE_KEY earlier (it was indeed the root cause as I had pasted it with newlines initially) but it hadn't taken effect. Ended up having to clear my authorization and re-authorize the app. (Had to both revoke my session in the GitHub app as well as clearing my browser cache & cookies.)

Thanks for your help!
