### ISSUE TITLE
Do I need to update to include your changes?

### ISSUE THREAD

**Issue by AntoineSoetewey** [giscus/giscus#252]
Hello,

I see that you are working quite a lot to develop giscus, thanks for that.

One question: as a user, do I have to update at some point or all your changes are automatically included without any actions on my side?

Regards,
Antoine

**Comment by laymonage** [comment]
Hey @AntoineSoetewey, good question.

Most updates should not require any changes on your side. However, we have added some new opt-in features in the past (and we'll add more in the future), such as multi-language support, origin checking, custom themes, etc. We try to provide a sensible default for each feature and make sure that existing sites that copied the `<script>` tag, at any point in time, does not break. It's also why we don't use any versioning for the script tag.

Does this answer your question?

**Comment by AntoineSoetewey** [comment]
Perfect, thanks again for the work!
