### ISSUE TITLE
Error on link with search parameters

### ISSUE THREAD

**Issue by DerGoogler** [giscus/giscus#260]
I can't login in to my GitHub by this link (https://dergoogler.com/?/safety/privacy-police/)

**Comment by laymonage** [comment]
It seems to work for me...?

![image](https://user-images.githubusercontent.com/6379424/142729841-26b5148e-ea95-4e07-8fa1-d175bf9a049e.png)

**Comment by laymonage** [comment]
Oh wait, looks like there's another bug I haven't fixed.

**Comment by DerGoogler** [comment]
Yeah, you're refreshed, right?

**Comment by laymonage** [comment]
@DerGoogler Yes, but you're logged in after that, aren't you?

**Comment by DerGoogler** [comment]
@laymonage I am not logged in after an page reload

**Comment by DerGoogler** [comment]
This normal?
![image](https://user-images.githubusercontent.com/54764558/142731127-3e1fa0bc-c02b-4dfb-b1f9-cf70839e2b28.png)

**Comment by DerGoogler** [comment]
or the npm package is not updated yet

**Comment by laymonage** [comment]
Which package are you using?

**Comment by DerGoogler** [comment]
I'm using the react version (1.0.1)

**Comment by laymonage** [comment]
Okay yeah that bug hasn't been addressed from the package, but I just pushed a fix that should fix the issue from server-side.

Are you still encountering the login issue?

**Comment by DerGoogler** [comment]
Looks like my own code make an issue

```ts
  public getMarkdownData(callback: Function) {
    if (window.location.search === "") {
      // If no search parameters
      axios
        .get(config.base.slug + config.base.defaultPage + config.base.file)
        .then((res) => {
          const data = res.data;
          if (typeof callback == "function") {
            callback(data);
          }
        });
    } else {
      axios
        .get(config.base.slug + getUrlParam(this.globalPram) + config.base.file)
        .then((res) => {
          const data = res.data;
          if (typeof callback == "function") {
            callback(data);
          }
        });
    }
  }
```

I think this makes the login issue

**Comment by DerGoogler** [comment]
i'll try it with `pathname`

**Comment by DerGoogler** [comment]
Please don't put the link into to an search param

**Comment by DerGoogler** [comment]
after an page reload is my `giscus-session` token invalid

**Comment by laymonage** [comment]
@DerGoogler I forcefully revoked the user tokens for security reasons. Could you verify that it now works? Also, the session value should no longer be included in the discussion search term.

**Comment by DerGoogler** [comment]
idk, but I'm still not singed in after page reload

**Comment by laymonage** [comment]
@DerGoogler Have you got it working? I can't replicate the issue.

**Comment by DerGoogler** [comment]
The comments are now on the right page. But the signd in bug is still.

**Comment by laymonage** [comment]
Then how did you manage to make this comment?

![image](https://user-images.githubusercontent.com/6379424/142757516-3607c540-92db-43b3-9a05-4d8ca8a2434f.png)

**Comment by DerGoogler** [comment]
@laymonage I just logged in.
Login works, but is not stay to be singed in

**Comment by laymonage** [comment]
@DerGoogler could you try the latest version of the react component (v1.1.1) and see if it works now?

**Comment by DerGoogler** [comment]
> @DerGoogler could you try the latest version of the react component (v1.1.1) and see if it works now?

i can try. Haven't long time not commited to this CMS project
