### ISSUE TITLE
Doesnt create new discussion on comment/reaction submit

### ISSUE THREAD

**Issue by snvmk** [giscus/giscus#261]
Hi, so, installed giscus on my site (https://snvmk.tk). but, when i submit new comment or reaction, it stucks. in console i see errors with 404, and warning that says that it will create new discussion, because existent one didnt found. but it doesnt create it... i created discussion for First post myself, and it works. but auto-creation would be good. thanks

**Comment by laymonage** [comment]
Did you remove a previously selected category? The `category-id` for your repository's `Comments` category should be `DIC_kwDOGYIJqc4B_9bv`, but your `<script>` tag specifies it as `DIC_kwDOGYIJqc3B_9bv` instead.

**Comment by snvmk** [comment]
Oooh, yea i will try replace it, after i eat. Thanks!19:57, 21 ноября 2021 г., "sag᠎e" ***@***.***>:
Did you remove a previously selected category? The category-id for your repository's Comments category should be DIC_kwDOGYIJqc4B_9bv, but your <script> tag specifies it as DIC_kwDOGYIJqc3B_9bv instead.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by snvmk** [comment]
yep, works now! thanks. mentioned you in commit github.com/snvmk/moonwalk
