### ISSUE TITLE
Improve documentation for private repositories support

### ISSUE THREAD

**Issue by antulik** [giscus/giscus#292]
Asked in https://github.com/giscus/giscus/discussions/291

Would be nice to add/fix support for private repositories.

Currently new comment creates new discussion, but discussion search is not working and no comments are displayed.

This is a failed request on page load:
```
GET http://localhost:3000/api/discussions?repo=antulik/test-giscus&term=Test&category=General&number=0&first=15
```

Response
```
404
{"error":"Discussion not found"}
```

**Comment by laymonage** [comment]
Thanks for testing it, @antulik! After looking into this, I noticed that it seems the limitation comes from GitHub's GraphQL search API when using an app-issued token.

Try the following query using a GraphQL client, e.g. https://hoppscotch.io/graphql (add `Authorization: Bearer <token>` header, replace `<token>` with `ghs_foo` or `ghu_bar`):

```graphql
{
  viewer {
    login
  }
  repository(owner: "antulik", name: "test-giscus") {
    discussion(number: 1) {
      id
      title
    }
    discussions(first: 100) {
      nodes {
        id
        title
      }
    }
  }
  search(type: DISCUSSION, first: 100, query: "repo:antulik/test-giscus Test") {
    discussionCount
    nodes {
      ... on Discussion {
        id
        title
      }
    }
  }
}
```

I got the following response:

```json
{
  "data": {
    "viewer": {
      "login": "giscus[bot]"
    },
    "repository": {
      "discussion": {
        "id": "D_kwDOGd9Yds4AOLq-",
        "title": "test"
      },
      "discussions": {
        "nodes": [
          {
            "id": "D_kwDOGd9Yds4AOLt7",
            "title": "Chris - Tech Knowledge Base"
          },
          {
            "id": "D_kwDOGd9Yds4AOLt1",
            "title": "Chris - Tech Knowledge Base"
          },
          {
            "id": "D_kwDOGd9Yds4AOLts",
            "title": "Chris - Tech Knowledge Base"
          },
          {
            "id": "D_kwDOGd9Yds4AOLtp",
            "title": "Chris - Tech Knowledge Base"
          },
          {
            "id": "D_kwDOGd9Yds4AOLsp",
            "title": "Chris - Tech Knowledge Base"
          },
          {
            "id": "D_kwDOGd9Yds4AOLso",
            "title": "Chris - Tech Knowledge Base"
          },
          {
            "id": "D_kwDOGd9Yds4AOLq-",
            "title": "test"
          }
        ]
      }
    },
    "search": {
      "discussionCount": 0,
      "nodes": []
    }
  }
}
```

The `search` query doesn't return any results. Meanwhile, accessing the discussions directly from the repository returns the discussions. This means that you should be able to use the "specific discussion number" mapping for the time being. I'll need to raise this issue to the hubbers.

P.s. the `search` query returns the results correctly if you use a personal access token (`ghp_foo`) or use their [GraphiQL Explorer](https://docs.github.com/en/graphql/overview/explorer).

**Comment by antulik** [comment]
@laymonage thank you for looking into that so quickly.

> This means that you should be able to use the "specific discussion number" mapping for the time being.

I can confirm specific discussion number works correctly with private repositories.

**Comment by ThomasFKJorna** [comment]
I don't think this is the issue actually. I was trying to adapt giscus to use private discussions on certain pages, but when I do the above query I do get nodes with both a personal and GHA access-token.

**Comment by rwenz3l** [comment]
Just wanted to confirm that number works and the default `pathname` or `url` does not with private repos. I will use that as a general comments section across our page for now, but would be cool if there is any workaround.

**Comment by laymonage** [comment]
> I don't think this is the issue actually. I was trying to adapt giscus to use private discussions on certain pages, but when I do the above query I do get nodes with both a personal and GHA access-token when searching in a private repo. Or, maybe, it was an issue and they fixed it in the meantime. I posted this in the feedback forum as well, but did not get a response: [github/feedback#8853](https://github.com/github/feedback/discussions/8853)

What app did you use to create the GitHub App access token? Also, what permissions does the app have? I just tried again and the search query still doesn't return any results.

**Comment by PabloYG** [comment]
Hey, I just came across this issue. In my case I'm not able to get a response from any of the 3 methods suggested above. All of them work fine when using GraphiQL explorer with a personal access token, but they fail when using Octokit's Auth with a GitHub App installation.

Any ideas?

**Comment by tefkah** [comment]
Extremely late update, apologies. I was probably not using the app access token but a user access-token, I can't show discussions from private repos when not logged in

**Comment by cbeauhilton** [comment]
A partial solution, using hugo, any templating language would work.

We have some password-protected posts, with a discussion living under Discussion # 123, and some public posts, with a discussion living under Discussion # 456. 

The password protection toggle is denoted in the frontmatter of each post (we use a postbuild step with `pagecrypt` to replace the html with an encrypted version), so the toggle is accessible here.

```
<script src="https://giscus.app/client.js"
       data-repo=""
       data-repo-id=""
       data-mapping="number"
       {{ if .Params.password_required }} true:
         data-term="123"
       {{ else }} false:
         data-term="456"
       {{ end }}
       data-reactions-enabled="1"
       data-emit-metadata="0"
       data-input-position="top"
       data-theme="preferred_color_scheme"
       data-lang="en"
       crossorigin="anonymous"
       async>
</script>
```

**Comment by trystanj** [comment]
FWIW, I reached out to Github directly. Over a few back-and-forths, this is the response I received:

>Thank you for reaching out. There is not an intentional limitation of App token scoping. The GraphQL and REST API endpoints are developed differently with different parameters and different inputs. Based on the conversations described in the links you have provided as well as some of my testing it does appear that GitHub App tokens are limited on this particular GraphQL endpoint.
>
> Thank you for providing further information. As the app in question is third party, testing is a little difficult to determine whether or not read and write access for GitHub Issues is necessary. Some endpoints do not respond to GitHub Apps and only are responsive to Personal Access Tokens. However, in testing similar endpoints, I have found that generally GitHub Issues requires read and write to modify discussions as they are apart of the same grouping.
> 
> If you can reach out to the Dev to enable read and write for GitHub issues and test to see if the information does display appropriately. If you are still running into issues, I am happy to run this to our engineering teams as a feature request.

So it seems they're open to fixing the discrepancy. I also see https://github.com/orgs/community/discussions/8853 has gotten some attention in the last few days as well (potentially related?).

I am happy to respond back to the issue I opened, or if it's easier for @laymonage to work with them directly, I'm sure GH can forward any relevant information!

**Comment by antn** [comment]
👋 Hi, engineer from GitHub here! Sorry about this bug, I've just deployed a fix for it. App tokens can now search for discussions in private repositories, as long as the app has the `discussions: read` permission.

If you're still running into any problems, please let me know!

**Comment by andrewcstewart** [comment]
Whoa thanks @antn !

Just to recap @laymonage, does this mean that all discussion mapping methods should now work with private repos, or would there be any adjustments needed on the giscus side?

**Comment by trystanj** [comment]
Thanks so much, @antn! I just tested giscus with a private repo (not using any of the "specific discussion number" or any other workarounds and it looks like it works great 😄

**Comment by laymonage** [comment]
Yep, just tested creating new discussions on a private repository through giscus and it works too! I guess I should update the homepage to add a better indicator when a repository is private and its implications. I'll keep this issue open until then.

To anyone interested in using giscus with a private repository, note that:
**If you install the official giscus instance on the repository, *anyone* will be able to "crawl" through the discussions if they know the `owner/repo` combination.** If your discussions contain sensitive information, I highly suggest that you self-host giscus and add additional security measures to prevent leaking information to unauthorized users.

That said, thank you very much @antn, you're a legend! Maybe #31 (aka https://github.com/orgs/community/discussions/3968) next? 👀

**Comment by LeetaoGoooo** [comment]
> Thanks so much, @antn! I just tested giscus with a private repo (not using any of the "specific discussion number" or any other workarounds) and it looks like it works great 😄

yeah,it can display comments from private repo now, but sadly, can't comment yet~

**Comment by laymonage** [comment]
> > Thanks so much, @antn! I just tested giscus with a private repo (not using any of the "specific discussion number" or any other workarounds) and it looks like it works great 😄
> 
> yeah,it can display comments from private repo now, but sadly, can't comment yet~

Are you sure the user has the permission to access the repository? I tested it the other day and it works fine...

**Comment by LeetaoGoooo** [comment]
> > yeah,it can display comments from private repo now, but sadly, can't comment yet~
> 
> Are you sure the user has the permission to access the repository? I tested it the other day and it works fine...

i gotcha ~ thx a lot!😘

**Comment by Willmish** [comment]
Hi @laymonage , stumbled onto this while trying to set up giscus for an internal repo (private sitting in an org). Other than GraphQL API, where can I find the dicussion Category id (`data-category-id` parameter)? Or could you point me to where the app https://giscus.app/ gets it from in code? I managed to get `data-repo-id` for it just by comparing the HTMLs, but no luck for the categoryID.

I know that giscus is mostly used for public-hosted webpages, but Im curious whether I can get it to work on an internal repo :)

**Comment by laymonage** [comment]
Hey @Willmish, the code is right here: https://github.com/giscus/giscus/blob/main/services/github/getDiscussionCategories.ts

I'm pretty sure there's nothing keeping you from using the https://giscus.app service to get those values (by entering the `user/repo` combination in the input box), but that does require you to install the giscus app on the repository.

**Comment by tmax22** [comment]
i can confirm that giscus-react works on private repos as well (no matter what the mapping is). just make sure you are using the correct `repoId`, and correct `category` and `categoryId` (also means that make sure the `category` you selected are correct, for example 
```jsx
<Giscus
          repo="<your-name/org>/<repo-name>"
          repoId="<repo-id>"
          category="Comments" // for example here i created a new category named 'Comments'
          categoryId="<category-id>" // E.g. id of "Comments"
          mapping="pathname" // here i use the pathname of the url
          term="Welcome to @giscus/react component!"
          strict="0"
          reactionsEnabled="1"
          emitMetadata="0"
          inputPosition="top"
          theme={colorMode}
          lang="en"
          loading="lazy"
        />
```

**Comment by a4z** [comment]
Is there documentation to follow for how to make it work on private repos? 
I use the normal Giscus setup, not the React one 

I have the app installed, Read and write access to discussions , and I think I have the repo(id) and category(id) filled out correct

I see the widget, can authenticate, but the post never gets created.

I see a 400 Bad Request, in the developer console, but I am far away from knowing anything about web development,
is there some way for me to figure out what I got wrong?

**Comment by LandonTClipp** [comment]
I can also confirm Giscus works fine in private repos. [The query from this blog post](https://qiita.com/shooter/items/d59fbb43d0f118c95092) can be copy-pasted into the Github GraphQL explorer, which will return the category IDs you need. So long as the Giscus app has been integrated in your private repo, it will have the ability to see everything.

Documentation should definitely be updated to make this clearer.

**Comment by antulik** [comment]
Looks like the issue was resolved on github end. Closing.
