### ISSUE TITLE
Error in self hosted version

### ISSUE THREAD

**Issue by Daniellop1** [giscus/giscus#334]
Hey, I was trying to deploy my own giscus instances but I get this error code in the widget : An error occurred: error: 0909006C: PEM routines: get_name: no start line.
When you put the repository name for checking if giscus can be used there I get another error even when the repository meets all the requirements. The error code is: Giscus cannot be used in this repository. Make sure all the above criteria are met.

Thanks in advance

**Comment by laymonage** [comment]
Hey, make sure that you've correctly specified your private key for the app in the `GITHUB_PRIVATE_KEY` environment variable.

**Comment by Daniellop1** [comment]
Thank you very much, I accidentally misspelled the certificate.

**Comment by Daniellop1** [comment]
I have checked and it keeps happening. I attach a screenshot of the terminal.
<img width="1440" alt="Captura de pantalla 2022-01-05 a las 22 54 29" src="https://user-images.githubusercontent.com/44546966/148295108-8f176c22-00dc-4e54-81de-6d7b3c5af459.png">
