### ISSUE TITLE
Comments are not loading when visiting other pages in a SPA

### ISSUE THREAD

**Issue by GorvGoyl** [giscus/giscus#357]
Comments are loaded if I do a full page reload however it's not working when I navigate some other pages in SPA. In [next.js](https://nextjs.org/), it's achieved by replacing only the required part of HTML, so the rest of the HTML content stays the same, including any third-party scripts. [learn more](https://nextjs.org/docs/routing/introduction). 

My current solution is to unload and load the script on every path change to make it work. Is there a way your script reloads the comments if there's a change in the URL path instead? That way, it'd be more performant as the script is loaded just once, even when visiting other pages in a SPA.

**Comment by laymonage** [comment]
You can load the script once, and change the search `term` dynamically by sending a `message` event to change the configuration.

See the [advanced usage guide](https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#parent-to-giscus-message-events) for more details.

**Comment by GorvGoyl** [comment]
I tried that but it looks like the `iFrame` element gets removed on page change so not able to send `Message` to it. Only the script tag remains on the page.

**Comment by laymonage** [comment]
In that case, you should put giscus in a component that doesn't get re-rendered on page change. You can also try the [react component](https://github.com/giscus/giscus-component), but it hasn't been updated for the latest features.

**Comment by RemixJazzCode** [comment]
I have same issue too. using Next.js, first fullloading is ok but when i using next/Link to other page and clicking back to comment page giscus is not loaded.

**Comment by laymonage** [comment]
Please use the [react component](https://github.com/giscus/giscus-component) and report back if you still find this issue.

**Comment by bepyan** [comment]
> You can load the script once, and change the search `term` dynamically by sending a `message` event to the `iframe` element to change the configuration.
> 
> See the [advanced usage guide](https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#parent-to-giscus-message-events) for more details.

Here is the example of sending `term` in Next.js.

```ts
useEffect(() => {
  const iframe = document.querySelector<HTMLIFrameElement>('iframe.giscus-frame');
  iframe?.contentWindow?.postMessage(
    { giscus: { setConfig: { term: router.asPath } } },
    'https://giscus.app',
  );
}, [router.asPath]);
```

**Comment by zakgrin** [comment]
I faced the same issue where comments are not loaded except when you refresh the page multiple times. But I found a solution to this based on this [comment](https://github.com/giscus/giscus/issues/336#issuecomment-1009551934). With some adjustments, my best working version is: 

```
.. raw:: html

    <script>
        let giscusTheme = localStorage.theme;
        let giscusAttributes = {
            "src": "https://giscus.app/client.js",
            "data-repo": "[ENTER REPO HERE]",
            "data-repo-id": "[ENTER REPO ID HERE]",
            "data-category": "[ENTER CATEGORY NAME HERE]",
            "data-category-id": "[ENTER CATEGORY ID HERE]",
            "data-mapping": "pathname",
            "data-strict": "1",
            "data-reactions-enabled": "1",
            "data-emit-metadata": "0",
            "data-input-position": "bottom",
            "data-theme": giscusTheme,
            "data-lang": "en",
            "data-loading": "lazy",
            "crossorigin": "anonymous",
            "async": ""};
        let giscusScript = document.createElement("script");
        Object.entries(giscusAttributes).forEach(([key, value]) => giscusScript.setAttribute(key, value));
        document.getElementById("comments").appendChild(giscusScript);
    </script>
```

However, one thing still missing is that when I change the theme, I need to refresh the page at least one time for the theme of comments to switch. Also note that in the last line, I specifiy the name of the html element by ID to append the giscus script. You need to check the elements in your case. This works as long as you have an element with the same id ("comments") at the end for your page.

**Comment by hungptsg** [comment]
One workaround is to wrap it in a component and trigger rerender using `term`. But still sometimes it doesn't reload properly.

```tsx
export function CommentSection(props: {
  componentName: string
}) {
  return (
    <Giscus
      id='comments'
      repo='hungptsg/mini-projects'
      repoId='R_kgDOOKxbMQ'
      category='General'
      categoryId='DIC_kwDOOKxbMc4CoNiH'
      mapping='pathname'

      term={`Welcome to ${props.componentName} comment!`}
      reactionsEnabled='1'
      emitMetadata='0'
      inputPosition='top'
      theme='dark'
      lang='en'
      loading='lazy'
    />
  )
}
```
