### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by MEgooneh** [giscus/giscus#360]
RTL languages need some additional changes.

**Comment by nschonni** [comment]
Just pulling the comment over from https://github.com/giscus/giscus/pull/239#issuecomment-963743237

> Not sure if something as simple as https://rtlcss.com/ would work, but probably doesn't need to happen in this PR

**Comment by laymonage** [comment]
Made some improvements in #626, could you let me know whether it's good or if I missed anything @MEgooneh? Right now only Arabic language is supported, though.

**Comment by laymonage** [comment]
Assuming all's good according to https://github.com/giscus/giscus/pull/622#issuecomment-1194006053.
