### ISSUE TITLE
giscus app refused to connect

### ISSUE THREAD

**Issue by nobodyme** [giscus/giscus#380]
![image](https://user-images.githubusercontent.com/22789194/151874607-a0d68892-4f99-427c-a5b0-231b79b8458f.png)

I get the above box when I try integrate giscus. Similar to #151. You can find my [code here](https://github.com/nobodyme/blog/blob/giscus/src/templates/blog-post.js). I tried to replace it with [your config](https://github.com/laymonage/base/blob/4080da98aaaca96d701972154d3038cc757bdb50/src/components/Giscus.tsx#L20), then it works, but unsure why it's not working with config I generated for my repo with the [giscus app](https://giscus.app/). Let me know, if you find something wrong. Have a nice day✌🏼

**Comment by laymonage** [comment]
Please provide a live website where the issue happens, otherwise it's hard for me to investigate the issue.

**Comment by laymonage** [comment]
Your [`giscus.json`](https://github.com/nobodyme/blog/blob/master/giscus.json) file is incorrectly configured.

The origin string should not include a trailing slash (do a `console.log(location.origin)` in the browser console on your website to see what it should look like). Also, for it to work locally, you need to add `http://localhost:8000` to your list of allowed origins. See [my `giscus.json`](https://github.com/laymonage/base/blob/main/giscus.json) for example.

**Comment by nobodyme** [comment]
Thanks @laymonage that helped ☮️

**Comment by laymonage** [comment]
> Thanks @laymonage that helped peace_symbol Just curious, any idea why it worked for me with your config?

Were you testing locally? If so, it's because I have `https://localhost:[0-9]+` in `originsRegex`, so the widget is allowed to run. If you deploy your website with that config, it shouldn't work because I haven't included your domain in `giscus.json`.

**Comment by nobodyme** [comment]
Yeah it was when I tested locally, I understand, thanks!
