### ISSUE TITLE
Error trying to comment without having created a discussion before

### ISSUE THREAD

**Issue by MasterKrab** [giscus/giscus#393]
I got this error when trying to comment without having created a discussion before.

`TypeError: Cannot read properties of undefined (reading 'addDiscussionComment')`

**Comment by laymonage** [comment]
https://github.com/MasterKrab/coded/commit/36f5a8e825ce2f8f79074b2ec5e4e501c438c496

You mistakenly set a `repo-id` value for `category-id`. Make sure that you have the correct values for both `repo-id` and `category-id`.

**Comment by MasterKrab** [comment]
> @MasterKrab [MasterKrab/coded@36f5a8e](https://github.com/MasterKrab/coded/commit/36f5a8e825ce2f8f79074b2ec5e4e501c438c496)
> 
> You mistakenly set a `repo-id` value for `category-id`. Make sure that you have the correct values for both `repo-id` and `category-id`, as they are required for creating a new discussion.

Solved, thank you very much.

**Comment by dodgio** [comment]
Another case where this error appears is when the giscus github app has not been given access to the repository you're trying to post discussions to. HTH
