### ISSUE TITLE
iFrameSizer is detected in my console - Vue

### ISSUE THREAD

**Issue by giwonn** [giscus/giscus#394]
![image](https://user-images.githubusercontent.com/72638829/153424789-4bc178c4-ff0f-4805-96d2-3229ca117bda.png)

Hello, It hasn't been a few days since I used this app.  
But this app is really amazing!
  
But unfortunately, These warning and error is occured in my website.  

First, the reason for the error is that there are no comments on this page.

And for the warnings... I don't know why that is occured.

How can I solve these problems?

**Comment by laymonage** [comment]
Hi, please update to `@giscus/vue` v1.1.1 and see if the issue is gone.

**Comment by giwonn** [comment]
> Hi, please update to `@giscus/vue` v1.1.1 and see if the issue is gone. The "Discussion not found" message is expected, unless you have created a discussion but for some reason giscus can't find it.

Thank you for reply quickly! 

I checked these issues again,  

I found only one warning. This warning still remains.
`[iFrameSizer][Host page: iFrameResizer0] [Tab Visable] IFrame(iFrameResizer0) not found`

And how can I remove the history of discussion in the `giscus`?
I think the reason for the problem is that I removed some discussions myself.

**Comment by laymonage** [comment]
> I checked these issues again,
> 
> I found only one warning. This warning still remains. `[iFrameSizer][Host page: iFrameResizer0] [Tab Visable] IFrame(iFrameResizer0) not found`
It seems your `yarn.lock` is still using v1.1.0: https://github.com/giwonn/giwonn.github.io/blob/a80a5f7bc64e95cb7c009209c4e049560d22ab2e/yarn.lock#L156-L157

Try running `yarn install` and commit the updated `yarn.lock` file.

> And how can I remove the history of discussion in the `giscus`? I think the reason for the problem is that I removed some discussions myself.

I'm sorry, I don't understand the question. Could you clarify? If you need to remove the discussion/comments, you can do so from GitHub. If you want to hide discussion on certain pages, make sure to not use the `<Giscus>` component in those pages.

**Comment by giwonn** [comment]
Thank you! Everything is work!
