### ISSUE TITLE
Cannot update reply and reaction of comment until refocus the window

### ISSUE THREAD

**Issue by alanaudi** [giscus/giscus#410]
[test post](https://www.alanaudi.com/blog/first-post)

https://user-images.githubusercontent.com/12343599/154672109-14a393ce-b197-41a2-8f6e-5282964e3502.mov

**Comment by laymonage** [comment]
Thanks, this is fixed in #412 and #413.

**Comment by alanaudi** [comment]
@laymonage thank for you work, this widget is really useful 🥳
