### ISSUE TITLE
Notify when new comment is made via Webhook?

### ISSUE THREAD

**Issue by AkashRajpurohit** [giscus/giscus#411]
Hi @laymonage firstly thank you for creating this project, I recently found out about this and immediately added this to my [blog](https://akashrajpurohit.com/blogs/) section as well. 

I was looking through the docs and was not able to find if there was anyway (in current world) where we can notify the users (website owners) when a new comment is posted (for moderation purposes maybe?)

I was thinking of a feature where if the user have provided any webhook URL/URLs, we can push the data to the webhook as well when we are publishing the data to the Github Discussions?

The reason to choose a webhook is that now anyone can choose their own way of receiving the notification like maybe via Slack webhooks, or a telegram bot maybe etc etc.

PS: If you are interested to have this feature to be something giscus should have then I would love to try adding this feature. :)

**Comment by laymonage** [comment]
GitHub already has webhook events for discussions (`discussion` and `discussion_comment`:
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#discussion

**Comment by AkashRajpurohit** [comment]
That makes sense, thanks.
