### ISSUE TITLE
don't let  discussion  url encoded.

### ISSUE THREAD

**Issue by TianBoxv587** [giscus/giscus#435]
Discussion title
![image](https://user-images.githubusercontent.com/91042118/158628626-27e1964a-e8fa-4a42-8de2-888efb3809eb.png)
Test  url
![image](https://user-images.githubusercontent.com/91042118/158628690-b48a5142-470d-4908-80b4-ab1d0cf48135.png)
Giscus generates URL-encoded headers and content, and I want to display the initial content.

**Comment by laymonage** [comment]
I'm afraid this isn't feasible without potentially breaking existing users. For example, if the user has a correct URL encoded pathname, e.g. `/posts/my%20notes/`, it would be decoded as `/posts/my notes/`, which could potentially break the search result on GitHub.

**Comment by TianBoxv587** [comment]
> I'm afraid this isn't feasible without potentially breaking existing users. For example, if the user has a correct URL encoded pathname, e.g. `/posts/my%20notes/`, it would be decoded as `/posts/my notes/`, which could potentially break the search result on GitHub.

What I mean is, can Chinese be left as it is, while the spaces and other symbols are still encoded. Like the `notes` in your reply are still not encoded by the url.
For example, `/post/radius 步骤` => `/post/radius%20步骤`

**Comment by laymonage** [comment]
I understand, but the thing is JavaScript's `encodeURIComponent`/`decodeURIComponent` functions do not have a way to include/exclude specific characters.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent#description

**Comment by npmrun** [comment]
@laymonage 
Maybe can use RegExp to replace string?
just like this: 
```
"post/ ,啊 啊/nn a啊 a".replace(/[^\dA-Za-z\u3007\u4E00-\u9FCB\uE815-\uE864\/]/g,(str)=>{
    return encodeURIComponent(str)
});
// oustput: post/%20%2C啊%20啊/nn%20a啊%20a
```
