### ISSUE TITLE
Go to anchor of Giscus form after login to Github

### ISSUE THREAD

**Issue by davidsneighbour** [giscus/giscus#436]
On a first visit to a Giscus instance I am presented with a login button for Github. Clicking it I am redirected to Github to login or automatically redirected twice to Github and back to the page. But the redirect ends me up at the top of the page, not the location of the giscus form. Is there a way to redirect to the form instead using an anchor?

**Comment by laymonage** [comment]
Implemented in #439.

You can do so by adding an `id` to the element that has the `giscus` class, e.g.

```html
<div id="example-comments-anchor" class="giscus"></div>
<script src="https://giscus.app/client.js
        ...>
```

**Comment by ryanwwest** [comment]
This is helpful, thanks for adding it.

> On a first visit to a Giscus instance I am presented with a login button for Github

I've noticed that even if I've authorized Giscus on my Github on other blogs, I still have to click the Login with Github button on every new one. This change makes that better, but ideally it would just auto-recognize if you've already logged in. I'm trying to figure out if that's a possibility or a good idea..

**Comment by ryanwwest** [comment]
Well, maybe this isn't possible since each site has its own Giscus app that needs to be separately authorized... Perhaps if they have a non GraphQL API in the future you'd just be able to be signed once to Github and it will autologin across all blogs...
