### ISSUE TITLE
weird spacing below the comments

### ISSUE THREAD

**Issue by davidsneighbour** [giscus/giscus#447]
There is a weird spacing going on after the coments section in no-comment as well as 1-or-more-comment situations:
![20220323-00:06:57_Selection_001](https://user-images.githubusercontent.com/83281/159536397-801ac015-ca3c-4a0d-b287-22abeb74e5c5.png)
![20220323-00:05:54_Selection_001](https://user-images.githubusercontent.com/83281/159536408-5ac925ca-dc0c-41d4-98c4-a665dee11404.png)

The code of the space between the comment form and the rest of the page is:

```
<div class="gsc-timeline input-top"><div class="gsc-comment">...</div></div>
```

If I remove `input-top` from the classes the spacing goes down. I am using Bootstrap 5, but there is nothing that might add any particular spacing to `input-top`. Maybe it's not required at that point?

If you want to test it on a live implementation go to [my site](https://kollitsch.de/blog/2022/100daystooffload/). 

Is this an issue with giscus CSS or does my own CSS somewhere break things?

**Comment by laymonage** [comment]
Fixed in #449.
