### ISSUE TITLE
[i18n][zh-CN] Is it possible to add a space between each part of DATE?

### ISSUE THREAD

**Issue by lkxed** [giscus/giscus#463]
<img width="264" alt="Snipaste_2022-04-01_23-35-20" src="https://user-images.githubusercontent.com/39257389/161295830-03137cc0-b0a0-4126-96f6-d6fbafb21446.png">

See the screenshot above. Is it possible to add spaces between Date parts?

So it would look like "2021 年 5 月 15 日" instead of "2021年5月15日".

This is more beautiful and better according to [Chinese writing conventions](https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.en.md#place-one-space-beforeafter-numbers).

**Comment by laymonage** [comment]
Thanks, fixed in #464.
