### ISSUE TITLE
Cannot upvote/downvote/cancel

### ISSUE THREAD

**Issue by anaclumos** [giscus/giscus#483]
![Screen Recording 2022-04-08 at 11 37 23 PM](https://user-images.githubusercontent.com/31657298/162560280-d7847cf4-3200-41fa-9ee5-33c17ce62d40.gif)

- Cannot `upvote`/`downvote`/`cancel`!
- It reflects the change for 1 second, then reverts to the original state.

**Comment by laymonage** [comment]
Duplicate of #31.
