### ISSUE TITLE
Help! Can not install giscus.

### ISSUE THREAD

**Issue by ycy1992911** [giscus/giscus#488]
Github link: https://github.com/ycy1992911/giscus

I have Giscus installed and with all the privileges granted, but I still get the error message: "An error occurred: giscus is not installed on this repository."

Is there anything I can do to solve this issue?

Many thanks,
Mike

**Comment by laymonage** [comment]
Works for me? https://github.com/ycy1992911/giscus/discussions/3#discussioncomment-2538750

Make sure the attributes of your `<script>` tag is correct.

**Comment by ycy1992911** [comment]
> Works for me? [ycy1992911/giscus#3 (comment)](https://github.com/ycy1992911/giscus/discussions/3#discussioncomment-2538750)
> 
> Make sure the attributes of your `<script>` tag are correct.

Thanks for your reply. I got the same error on https://giscus.app/ as well.

**Comment by laymonage** [comment]
You're supposed to enter `ycy1992911/giscus`.

**Comment by ycy1992911** [comment]
> You're supposed to enter `ycy1992911/giscus`.

omg！That works! Thank you very much!

**Comment by GavinRay97** [comment]
Just as a heads up, it wasn't clear to me that it wanted the short-form repo URL and not the canonical HTTP URL

I was blocked on this and confused for a while until I found this issue luckily
