### ISSUE TITLE
Cannot use giscus on my repository

### ISSUE THREAD

**Issue by presentzeng** [giscus/giscus#491]
Hi Team, i have followed the self-hosting instruction, and have checked the three demands.
1. My repo is public:  https://github.com/presentzeng/giscus
2. The giscus app installed, i can see it in my repo's Github apps
3. The discussion feature is enabled on my repo

but when i input: presentzeng/giscus, it still shows : Cannot use giscus on this repository. Make sure all of the above criteria has been met.

Could you help me on it, Tks a lot

**Comment by laymonage** [comment]
Where's your deployed instance of the self-hosted giscus application? I can't help you if I can't access it. Make sure you use that instance to input your repo, not on https://giscus.app.

If you are inputting it on https://giscus.app, there's no need to self-host it, but you have to install it on your repository (https://github.com/apps/giscus/installations/new). I just checked and my giscus instance is not installed on your repository.

**Comment by presentzeng** [comment]
Hi laymonage, tks for your help, it works now! let me write down my issue in case other users encounter the same.
actually i misunderstood the procedure, i installed it by following the self-hosting procedure
![image](https://user-images.githubusercontent.com/8578962/163540022-4a7d238d-e013-4841-8ad4-7d522288b827.png)
and i thought the config of https://giscus.app/ is also part of self-host, actually it is two different way, So i just have to into: https://github.com/apps/giscus and install the app for my repo, then it will be ok. Again tks laymonage, what a good comment tool!
