### ISSUE TITLE
Manually load using Swup

### ISSUE THREAD

**Issue by IeuanWalker** [giscus/giscus#502]
Hi,

I've implemented this on my blog and it's great.

But I'm just implementing page transitions using [Swup](https://swup.js.org/), this library [highjacks the page's normal page lifecycle](https://swup.js.org/getting-started/reloading-javascript) preventing giscus from working. 

Is there a manual method that can be called to trigger it too load?

**Comment by laymonage** [comment]
I suppose you can [copy the client script](https://github.com/giscus/giscus/blob/main/client.ts) and modify it to add the event handlers for Swup.

Or you can also try the web component instead: https://github.com/giscus/giscus-component#using-the-web-component

**Comment by IeuanWalker** [comment]
thanks @laymonage, the web component works
