### ISSUE TITLE
Sync theme with localStorage instead of prefers-color-scheme

### ISSUE THREAD

**Issue by nikhilweee** [giscus/giscus#503]
I have a dark/light mode theme toggle on my website. The way I implement it is by using a localStorage item (let's call it `pref-theme`). My website switches to light/dark mode based on the value of `pref-theme`. I want giscus to respect the theme toggle. 

Right now I have settled on the following solution. I listen to `message` events, and try to send a message to `giscus` whenever I receive a message event. The problem is that this doesn't work 100% of the time. Any suggestions would be appreciated.

```js
    function changeGiscusTheme() {
        // theme can either be `dark` or `light`.
        let theme = localStorage.getItem("pref-theme");
        let message = { setConfig: { theme: theme } };
        let iframe = document.querySelector('iframe.giscus-frame');
        // iframe might not be loaded by the time this function is called.
        if (iframe) {
            iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
    }

    function handleMessage(event) {
        if (event.origin !== 'https://giscus.app') return;
        if (!(typeof event.data === 'object' && event.data.giscus)) return;
        changeGiscusTheme();
    }
      
    window.addEventListener('message', handleMessage);
```

P.S. I know that I can use `preferred_color_scheme` as the theme for giscus but that takes away the functionality of the toggle.

**Comment by laymonage** [comment]
Using message events is the only way. The widget is loaded in an iframe, so it uses its own `localStorage` (for https://giscus.app) and has no way to access your site's `localStorage`.

> The problem is that this doesn't work 100% of the time.

Could you elaborate on that? It seems to work every time for me and the others. In fact, the same mechanism is also used when you try out the themes on the main website.

Looking at your code, *handling* the message event is not necessary (and doesn't do anything) unless you tell giscus to emit the discussion metadata. This shouldn't be necessary if you just want to change the theme.

Anyway, maybe you tried to click on the toggle before the iframe is loaded? If so, I suppose you could supply `data-theme` dynamically as suggested here: https://github.com/giscus/giscus/issues/336#issuecomment-1009551934

Some other comments in there might also be helpful.

If it still fails, you might want to try the [web component](https://github.com/giscus/giscus-component#using-the-web-component) instead. With that, you only need to change the element's attribute, the component will then send the message event to the iframe.

**Comment by nikhilweee** [comment]
> The problem is that this doesn't work 100% of the time.

Unfortunately I am not able to reproduce the irregularities. Aplogies for this, maybe I was doing something wrong / using a slightly modified version of this code. Right now the theme seems to be consistent. 

Thank you for your suggestions with other ways to deal with this, that's exactly why I came here. However, at the moment, things are working fine so I will leave it be. I'll close this right now and come back if I face any issues. Thanks!
