### ISSUE TITLE
Cannot transfer discussions (giscus-related?)

### ISSUE THREAD

**Issue by brycewray** [giscus/giscus#510]
I have two public repos set up for giscus. I wanted to transfer existing discussions from one repo to another, but cannot (see https://github.com/github/feedback/discussions/3381). My question: do you know whether it would help if I temporarily disabled giscus access to one or both of the repos? Does giscus's connection even have any effect on the ability to transfer discussions? Or is this simply a GitHub Discussions glitch?

Thanks in advance for any related info you could provide.

**Comment by laymonage** [comment]
I doubt giscus has any effect on this. It only interacts with your repository's discussions when it creates new discussions, comments, replies, and adding/removing reactions. Anything else from the discussions feature itself is untouched.

It's likely there are some issues on GitHub's side when they transfer the discussions. One thing I want to make sure though: is giscus installed on both repositories? If not, try installing it first. Maybe GitHub refuses to transfer the discussions if there are discussions/comments made through giscus but it is not installed on the target repository.

If you have already installed giscus on both repositories, then I can't think of any other causes. There's nothing else we can do other than waiting for GitHub to fix it.

**Comment by brycewray** [comment]
Thanks! And giscus definitely is installed on both repos. So, yes, we'll have to hope GitHub fixes this, soon. Given that these other reports are many months old, I'm not optimistic. :-(

**Comment by laymonage** [comment]
Other possible workaround: convert the discussion into an issue first, then transfer the issue, and then convert the issue into a discussion. Any threads will be flattened though, and it might still fail somewhere along the way, so maybe you want to use a temporary repository to test this first.

**Comment by brycewray** [comment]
I actually did consider the "try it somewhere else" approach, but haven't done it yet because, as you say, I feared it would be stuck there.However, my discussions are small enough that I can risk flattening then with a conversion to issues, so I'll try that. Thanks.

**Comment by brycewray** [comment]
Follow-up: I tried converting two discussions to issues, then transferring them, then converting them back to discussions. Those went through, but as of now it appears the comments got lost in the process (even though the GitHub messages indicated that they would be retained). It was worth a try, though.

**Comment by laymonage** [comment]
Workaround found at https://github.com/github/feedback/discussions/3381#discussioncomment-2655724. Thanks for the report!

**Comment by brycewray** [comment]
And, again, thank you, @laymonage !
