### ISSUE TITLE
Dev Mode

### ISSUE THREAD

**Issue by JohnGuan** [giscus/giscus#512]
I have to say, this is a very cool project!
I'm adding giscus to my docusaurus site and am using the react component.
I was wondering if there could be a dev mode parameter so giscus could know what dev mode is so it doesn't create sites that point to localhost?
Thanks a lot to the author for bringing such an amazing project!

**Comment by davidsneighbour** [comment]
Why don't you change the identifier from URL to Title? In that case, it's not saved as localhost.

**Comment by laymonage** [comment]
> The current practice is to ensure that there is no interaction with the comments section during testing. 😂

Then... just don't include the script on your dev environment?

**Comment by JohnGuan** [comment]
> Then... just don't include the script on your dev environment?

😂 This should be the easiest way to do it.

I'll try creating a comment placeholder in the dev environment.
