### ISSUE TITLE
Cannot use giscus on this repository. Make sure all of the above criteria has been met.

### ISSUE THREAD

**Issue by NewStorm-0** [giscus/giscus#513]
Cannot use giscus on this repository. Make sure all of the above criteria has been met.
But my repository meets all three of criteria. I have tried to change a repository. But it still can't worked.

**Comment by laymonage** [comment]
What did you write in the input box? Make sure not to use https://github.com/, e.g. if your repository is https://github.com/NewStorm-0/NewStorm-0.github.io, enter `NewStorm-0/NewStorm-0.github.io`.

**Comment by NewStorm-0** [comment]
> What did you write in the input box? Make sure not to use https://github.com/, e.g. if your repository is https://github.com/NewStorm-0/NewStorm-0.github.io, enter `NewStorm-0/NewStorm-0.github.io`.

Oh, yes. I made a mistake like this.  After deleting "https://github.com/", it showed I can use it. Thank you!
