### ISSUE TITLE
[Error] Discussion not found.

### ISSUE THREAD

**Issue by giwonn** [giscus/giscus#530]
![image](https://user-images.githubusercontent.com/72638829/167863365-f19459be-dc85-4126-9759-77a737c3aefa.png)

I think some comments already deleted, but giscus api has their history.

How can I resolve this error?

**Comment by laymonage** [comment]
This is expected if the discussion does not exist for the page you're currently viewing. If you leave a new comment/reaction, giscus will automatically create the discussion, and if you reload the page, the "error" goes away because now the discussion exists.

**Comment by giwonn** [comment]
Okay, I will try your suggestions. Thank you!

**Comment by mkubdev** [comment]
Hio @giwonn, i have the same issue. Even on the giscus.app demo website. Did you manage to fix it?

**Comment by giwonn** [comment]
Hi, @mkubdev. This error occurs when there are no comments on the page your are viewing.  
The only way to remove this error is to comment on the page.  
If my explanation wasn't enough, fell free to tell me. Thank you :)

**Comment by mkubdev** [comment]
Hi @giwonn. Thanks for the reply 🤗 The explanation is really good. It's working now!

**Comment by fritx** [comment]
Occasionally meet this 404 errors, and sometimes successful 😕

**Comment by Hillkinsh** [comment]
The same issue. How can I fix it?
https://giscus.app/api/discussions?repo=Hillkinsh%2Fgiscus&term=index&category=General&number=0&strict=false&last=15

**Comment by fritx** [comment]
any thoughts? i think it should not be 404 when discussion not found, but a 200 or something

**Comment by BrunoElo** [comment]
I'm still having this issue at https://www.brunoelo.com/blog/module-scoped-styling-in-angular-13. Try leaving a comment. I'm using the title

**Comment by MatiasColladoCA** [comment]
I had the same problem and tried everything. It works to create the discussion from Github but the idea is that by default Giscus creates the discussion if someone comments and the discussion doesn't exist. That is what is not working in my case.
