### ISSUE TITLE
Allow Sorting Comments by Top

### ISSUE THREAD

**Issue by LukePrior** [giscus/giscus#542]
This feature exists in the discussions tab but I'm not sure how hard it would be to include with giscus.

![image](https://user-images.githubusercontent.com/22492406/168927901-da56be74-844e-4087-967f-66c629a381d9.png)

**Comment by laymonage** [comment]
See https://github.com/giscus/giscus/issues/75#issuecomment-841810592 and https://github.com/github/feedback/discussions/15432#discussion-4028726.
