### ISSUE TITLE
correct http response code from `404` to `204`

### ISSUE THREAD

**Issue by dipakparmar** [giscus/giscus#552]
4XX error codes are more towards when the resource is trying to retrieve does not exist, in the API use case - the API path is first to apply to this context, and the API path is correct, just there is no data. As the request made was correct, it should send 204. 

According to RFC 2616, [HTTP status code `404` ](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#:~:text=The%20server%20has%20not%20found%20anything%20matching%20the%20Request%2DURI.)

> **The server has not found anything matching the Request-URI**. No indication is given of whether the condition is temporary or permanent. The 410 (Gone) status code SHOULD be used if the server knows, through some internally configurable mechanism, that an old resource is permanently unavailable and has no forwarding address. This status code is commonly used when the server does not wish to reveal exactly why the request has been refused, or when no other response is applicable.

where [HTTP status code `204`](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#:~:text=10.2.5%20204%20No%20Content)

> The server has fulfilled the request but does not need to return an entity-body, and might want to return updated metainformation. The response MAY include new or updated metainformation in the form of entity-headers, which if present SHOULD be associated with the requested variant.
> 
> If the client is a user agent, it SHOULD NOT change its document view from that which caused the request to be sent. This response is primarily intended to allow input for actions to take place without causing a change to the user agent's active document view, although any new or updated metainformation SHOULD be applied to the document currently in the user agent's active view.
> 
> The 204 response MUST NOT include a message-body, and thus is always terminated by the first empty line after the header fields.

### Possible changes:

- updating status to 204
https://github.com/giscus/giscus/blob/2894c5afe34b3c4ae1de204918185efb5e9646fa/pages/api/discussions/index.ts#L83

- checking 204 status vs checking message body
https://github.com/giscus/giscus-component/blob/853d920bb24f93e6035bcb65068f6505471a7ad0/web/src/giscus.ts#L186

there might be more places to update, so far I found only this two to update as I just started using giscus. 😁

Also, thank you for creating discus! ❤️

**Comment by birjj** [comment]
I can't say I agree with the claim here. HTTP code 204 falls under the 2XX success category - it indicates that the request was a success, but the server doesn't need to return any data. [HTTP code 404](https://www.rfc-editor.org/rfc/rfc9110.html#name-404-not-found) is a 4XX client error code, indicating that

> the origin server did not find a current representation for the [target resource](https://www.rfc-editor.org/rfc/rfc9110.html#target.resource) or is not willing to disclose that one exists.

This is the case when the requested discussion doesn't exist. You can see further discussion on this [e.g. here](https://softwareengineering.stackexchange.com/questions/322951/should-i-return-a-204-or-a-404-response-when-a-resource-is-not-found), or see the superseding specification's description [here](https://www.rfc-editor.org/rfc/rfc9110.html)

**Comment by laymonage** [comment]
Thanks for the suggestion. I tinkered around with your PR the other day, and the change is not as simple as

```diff
- res.status(404).json({ error: 'Discussion not found' }); 
+ res.status(204).json({ error: 'Discussion not found' });  
```

because as you wrote,

> The 204 response MUST NOT include a message-body, and thus is always terminated by the first empty line after the header fields.

In the end, I managed to get it working after making adjustments in other places, but I think I have to agree with @birjj here. Additionally, in giscus'/GitHub's case, the search query can also be made using a specific discussion number (which acts as an ID). A REST API typically throws a 404 if you try fetching an object using an ID that does not exist.

**Comment by YexuanXiao** [comment]
Can the error code be made configurable? I have no issue with 404, but Chrome unconditionally treats 404 as an error and prints messages in the console, which is annoying.

**Comment by birjj** [comment]
@YexuanXiao I can sympathize with the frustration, but I don't think the correct response is for applications to implement workarounds for a UI issue with Chrome. 404 is undoubtedly the correct response code when a resource isn't found, and the Chromium team's weird design choice shouldn't force anyone to divert from the HTTP protocol - that'd be an overreaching hack.

There seems to be a tiny bit of recent activity on [the Chromium issue on the behavior](https://issues.chromium.org/issues/40788570) - perhaps it'd be worth adding to the choir there?

Other options, depending on your situation:
- [StackOverflow answer showing how it can be suppressed by the client (Chrome unfortunately offers no option to actually disable it, only supress it)](https://stackoverflow.com/a/76249624)
- [This StackOverflow post with suggestions on hacky workarounds, if you _really_ need this gone](https://stackoverflow.com/a/75848002)
