### ISSUE TITLE
[Question] Sort by Upvotes?

### ISSUE THREAD

**Issue by GL513** [giscus/giscus#554]
Hello. I discovered Giscus only a week ago and had a question. I understand that currently Github itself cannot sort by upvotes, but since Giscus is third-party, is there any way that Giscus itself can do this?
Thanks for all of your work!

**Comment by laymonage** [comment]
Unfortunately no, the API doesn't give an option to sort the comments at all, and we can't sort by upvotes without fetching all the comments beforehand. (We use pagination when there is a lot of comments.)

**Comment by GL513** [comment]
Alright, thank you :)
