### ISSUE TITLE
Having trouble installing Giscus

### ISSUE THREAD

**Issue by osfanbuff63** [giscus/giscus#578]
**My repo**: [osfanbuff63/osfanbuff63.github.io](https://osfanbuff63.github.io)

I can't seem to get Giscus to work correctly on my repository. This is a Jekyll site using the Minimal Mistakes theme, published to GitHub Pages. I have gone through the full setup process on [giscus.app](https://giscus.app) successfully, and applied it to my repo, but it still won't deploy. Am I doing something wrong?

**Note**: I have not gotten any errors or such either.

**Comment by laymonage** [comment]
Your template checks for `site.giscus` in the config:
https://github.com/osfanbuff63/osfanbuff63.github.io/blob/ffcf75af5ddf1ecaa7eeecd3ad843deed0b86540/_includes/my_comments.html#L21

But your giscus config is nested under `site.comments`:
https://github.com/osfanbuff63/osfanbuff63.github.io/blob/ffcf75af5ddf1ecaa7eeecd3ad843deed0b86540/_config.yml#L62-L69

You should do this change:

```diff
- {% assign giscus = site.giscus %}
+ {% assign giscus = site.comments.giscus %}
```

Moreover, you have the following check:

```
{% if giscus.repo %}
```

but you don't have a `repo` key under the `giscus` key in your config. You should use the existing `repository` key in `site` instead (or move it into `site.giscus` and rename it to `repo`). You need to change it to

```diff
- {% if giscus.repo %}
+ {% if site.repository %}
```

and the following:

```diff
- data-repo={{ giscus.repo }}
+ data-repo={{ site.repo }}
```

**Comment by osfanbuff63** [comment]
Thanks a lot! Looks like I just messed up copy and paste lol. Still doesn't seem to be working right with those changes, but I'll take a closer look and see if I made any other mistakes like that.

**Comment by laymonage** [comment]
Fixed in https://github.com/osfanbuff63/osfanbuff63.github.io/pull/9.
