### ISSUE TITLE
Two discussions were created for the same page

### ISSUE THREAD

**Issue by misode** [giscus/giscus#579]
Not a big deal and this only happened once, but Giscus just created two discussions when a user on my site added a reaction

The links: https://github.com/misode/misode.github.io/discussions/247 and https://github.com/misode/misode.github.io/discussions/248

**Comment by laymonage** [comment]
Thanks, the user probably clicks the button a second time while the discussion was still being created. I'll see if I can add a check to help prevent this.

**Comment by laymonage** [comment]
Attempted fix at #623, let me know if this happens again.
