### ISSUE TITLE
Cannot Comment on `@giscus/react`

### ISSUE THREAD

**Issue by RudraSen2** [giscus/giscus#580]
Hello, I am using `@giscus/react` in my Docusaurus v2 React App. After I'm clicking on the Comment button, it goes greyed out and does not get commented and a disabled cursor is also there when hovered.
Screenshot Below:

![image](https://user-images.githubusercontent.com/91307601/174639018-9130c7b0-62d0-4512-bd03-8a49dd7d56ba.png)

**Comment by laymonage** [comment]
You defined your props incorrectly in your MDX files:

https://github.com/Comp-Labs/comp-labs-website/blob/main/blog/posts/install-macos-ventura-on-windows-using-virtualbox/install-macos-ventura-on-windows-using-virtualbox-16.mdx?plain=1#L394-L407

`repo-id` should be `repoId`, `category-id` should be `categoryId`, etc.
