### ISSUE TITLE
Paste/drag-and-drop images into the composer á la Github composer

### ISSUE THREAD

**Issue by Kimeiga** [giscus/giscus#583]
Sorry no idea how possible this is but I think it would be quite cool

<img width="961" alt="image" src="https://user-images.githubusercontent.com/20587215/176066628-7fd84c4f-cecb-42c7-b783-7d4609fb5119.png">

"Attach files by dragging & dropping, selecting or pasting them." is a cool feature available on the composer, and I was wondering if there was a way to add this feature to the composer of Giscus. 

Does Giscus take the standard Github composer and remove this feature; or does it build the composer from the ground up to match, and implementing this feature would require finding the github  user-images.githubusercontent api?

Thank you so much for your work!

---

as a reminder, the ux is when you have an image in your clipboard, you paste it into the text area, there's a brief moment while it's uploading and there's an empty markdown image inserted at your cursor, and that becomes replaced by an image after the image has been uploaded

`![image](https://user-images.githubusercontent.com/20587215/176065832-ac177808-1b62-41bb-aa31-d4f65e1c2f66.png)` 
goes to 
![image](https://user-images.githubusercontent.com/20587215/176065832-ac177808-1b62-41bb-aa31-d4f65e1c2f66.png)

**Comment by laymonage** [comment]
Thanks!

> Does Giscus take the standard Github composer and remove this feature; or does it build the composer from the ground up to match, and implementing this feature would require finding the github user-images.githubusercontent api?

It's built from scratch. The main blocker for implementing this is that GitHub doesn't provide a publicly accessible API to upload images. See #197.

**Comment by Kimeiga** [comment]
It appears that the token is used in the call to https://github.com/upload/policies/assets
I can't find a place the cookie is used there
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/20587215/176096910-09aa9267-2e8b-40c7-ad8a-6c179a132ddb.png">

Here's the OPTIONS. I can't exactly tell what's going on, but I'm not sure if there's a cookie here
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/20587215/176097059-737efdf1-74ca-49ba-8991-007bf87d86f6.png">
continued:
<img width="805" alt="image" src="https://user-images.githubusercontent.com/20587215/176097173-4488c091-34cd-4ad7-aaab-b3d62cffa110.png">

Here's the POST
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/20587215/176097279-9cd862ad-619e-4bc5-a7e4-d9cc33e73547.png">

Here's the PUT
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/20587215/176097345-ba99bd3f-9388-4c03-ad2f-2337a373c7ec.png">

So not sure where the cookie might be here, but I'm also totally unfamiliar so I figured I would just show you what comes up in the network tab when I paste an image from the clipboard into the composer

**Comment by laymonage** [comment]
The `authenticity_token` is a CSRF token, which means it's entirely different from an API access token.

The cookie is always sent in requests sent to `github.com`, in this case `https://github.com/upload/policies/assets` and `https://github.com/upload/assets/<asset_id>`.

See:

<img width="822" alt="image" src="https://user-images.githubusercontent.com/6379424/176106999-4b3df51b-6602-4384-b20f-1eb0fb1e9f43.png">

<img width="822" alt="image" src="https://user-images.githubusercontent.com/6379424/176107171-7c4079c4-b1b8-4d96-bf7f-7960d2f3eb97.png">

The flow is:
- `POST` to `https://github.com/upload/policies/assets` with the headers (`Cookie`, `Referer`, etc.) and the following payload:
  ```ts
  {
    "name": string;
    "size": number;
    "content_type": ContentType;
    "authenticity_token": string;
    "repository_id": number;
  }
  ```
  The `authenticity_token` is retrieved from the HTML rendered by GitHub. See the `value` attribute of `<input type="hidden" data-csrf="true" class="js-data-upload-policy-url-csrf">` inside the `<file-attachment>` custom element.
- GitHub returns a response with the following format:
  ```ts
  {
      "upload_url": string;
      "header": {};
      "asset": {
          "id": number;
          "name": string;
          "size": number;
          "content_type": ContentType;
          "href": string;
          "original_name": string;
      };
      "form": {
          "key": string;
          "acl": string;
          "policy": string;
          "X-Amz-Algorithm": string;
          "X-Amz-Credential": string;
          "X-Amz-Date": string;
          "X-Amz-Signature": string;
          "Content-Type": ContentType;
          "Cache-Control": string;
          "x-amz-meta-Surrogate-Control": string;
      };
      "same_origin": boolean;
      "asset_upload_url": string;
      "upload_authenticity_token": string;
      "asset_upload_authenticity_token": string;
  }
  ```
- A `POST` request is sent to `upload_url` (AWS S3). The data in `form`, plus a `file` that maps to the binary data of the file, is the payload of the request.
- AWS returns `204`.
- A `PUT` request is sent to `asset_upload_url`, with the headers and the following payload:
  ```ts
  {
     "authenticity_token": string;
  }
  ```
  Where the `authenticity_token` value is the `asset_upload_authenticity_token`.
- GitHub returns a response with the following format:
  ```ts
  {
    "id": number;
    "name": string;
    "size": number;
    "content_type": ContentType
    "href": string;
    "original_name": string | null;
  }
  ```
- The `name` and `href` is put into the composer.

Even if we somehow can imitate the requests and GitHub doesn't check the cookie, there's a possibility that GitHub checks for the `Referer` header, making it impossible to fake it from a browser.

**Comment by laymonage** [comment]
Closing in favor of #197.
