### ISSUE TITLE
Issue with Joomla article

### ISSUE THREAD

**Issue by N6REJ** [giscus/giscus#591]
I'm very confused.  I got everything configured but the article is blank.  Ideally, I would like all discussions but at least the announcements one.  What do I need to change?
```
<script src="https://giscus.app/client.js"
        data-repo="Bearsampp/Bearsampp"
        data-repo-id="R_kgDOGS08ow"
        data-category="Announcements"
        data-category-id="DIC_kwDOGS08o84B_70H"
        data-mapping="url"
        data-reactions-enabled="1"
        data-emit-metadata="1"
        data-input-position="bottom"
        data-theme="light"
        data-lang="en"
        crossorigin="anonymous"
        async>
</script>
```
http://bearsampp.com/index.php/discussions

**Comment by laymonage** [comment]
The page shows 404 for me, so I can't investigate.

**Comment by N6REJ** [comment]
@laymonage I'm so sorry, I got frustrated and turned it off I guess... 
http://bearsampp.com/announcements
it's back and I made sure the script matches.

**Comment by laymonage** [comment]
I can't find the `<script>` tag in the rendered HTML though?

<img width="526" alt="image" src="https://user-images.githubusercontent.com/6379424/177230646-a9170362-e18d-4f92-88f4-b5150bcaf1db.png">

**Comment by N6REJ** [comment]
![image](https://user-images.githubusercontent.com/1850089/177356854-da7297dd-a702-47f4-b62c-2cd8ef72a4f8.png)
![image](https://user-images.githubusercontent.com/1850089/177356975-d3641346-afd8-49df-b8c6-a3ad86fd9533.png)

**Comment by laymonage** [comment]
Umm... it seems you're missing the `src` attribute?

**Comment by N6REJ** [comment]
SNAP!.. good eyes... its stripping it out on save!

**Comment by N6REJ** [comment]
I'm doing something wrong cause all I'm getting is the comment part not the announcements.

**Comment by N6REJ** [comment]
I moved it here http://bearsampp.com/news/announcements since status is working

**Comment by laymonage** [comment]
If by announcements you mean the discussion's original post, then it's currently not possible. We only show the discussion's comments.

**Comment by N6REJ** [comment]
darn.  ok ty.
