### ISSUE TITLE
FEATURE: allow newest comment first

### ISSUE THREAD

**Issue by N6REJ** [giscus/giscus#592]
Is it possible to have the newest comment(s) right under the top new comment box?
http://bearsampp.com/news/status

**Comment by laymonage** [comment]
There's a "Oldest|Newest" button that users can click to switch the ordering. You can also set the default comment order in `giscus.json` in your repository root: https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#defaultcommentorder

**Comment by N6REJ** [comment]
works great.. tyvm.
