### ISSUE TITLE
An optimization suggestion for IOS

### ISSUE THREAD

**Issue by Pathsis** [giscus/giscus#613]
If the font size of the input box is smaller than **16px**, the input box will be **zoomed**  when you click on it, this seems to be a "rule" of IOS, if you adjust the font to make it bigger than or equal to 16px, it will improve the experience.

https://user-images.githubusercontent.com/72077265/179894165-078cb99d-5050-46b5-99c6-bd7b158b7431.MP4

**Comment by laymonage** [comment]
Should be fixed by #625, could you confirm?

**Comment by Pathsis** [comment]
> Should be fixed by #625, could you confirm?

I cannot complete the authorization properly.

![IMG_1054](https://user-images.githubusercontent.com/72077265/180640887-a046471c-1599-4167-b729-85dec16831a3.PNG)

**Comment by laymonage** [comment]
That's strange, I don't think I touched anything that would break it. What website are you signing in from? Could you try again?

**Comment by Pathsis** [comment]
@laymonage Looks like it's officially working. Now Giscus on my site is very perfectly avoided while this problem. Thanks for the timely disposal!

https://user-images.githubusercontent.com/72077265/180641070-e5cae2bb-2605-428e-a767-445dfb98aee5.MP4

**Comment by Pathsis** [comment]
> 这很奇怪，我不认为我碰过任何会破坏它的东西。您从哪个网站登录？你能再试一次吗？

I tested the first link at the bottom of this page: [giscus-giscus.vercel.app](https://giscus-giscus.vercel.app/) But Giscus is now working perfectly on my site!

**Comment by Pathsis** [comment]
> That's strange, I don't think I touched anything that would break it. What website are you signing in from? Could you try again?

I tested the first link at the bottom of this page: [giscus-giscus.vercel.app](https://giscus-giscus.vercel.app/) But Giscus is now working perfectly on my site!

**Comment by laymonage** [comment]
Ah, yes, the preview deployments cannot be used for signing in because each domain needs to be manually registered, and I've only registered the production and (local) deployments.

Thanks for reporting back!
