### ISSUE TITLE
Toggle Giscus theme from dark to light depending on user preference

### ISSUE THREAD

**Issue by okikio** [giscus/giscus#643]
Is there a way to toggle Giscus' theme from light to dark depending on user preferences? e.g. If the page has a `dark` class added to the page HTML, giscus turns dark, otherwise giscus uses color-scheme preferences.

**Comment by Andre601** [comment]
I agree... I always get nearly blinded whenever I visit the giscus website... Having it set the theme based on your preferences would be wonderful.

**Comment by laymonage** [comment]
@okikio This is already possible by sending a message to the iframe. See the [advanced usage guide](https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#parent-to-giscus-message-events) and comments in #336 and #134.

I've also changed the default theme to `preferred_color_scheme` in #664. Cheers.
