### ISSUE TITLE
Customize "Sign in with Github" logic

### ISSUE THREAD

**Issue by AmazingAng** [giscus/giscus#651]
My website: https://wtf.academy already has a built-in "log in with github". How can I combine it with the giscus "sign in with Github" button? thanks!

**Comment by laymonage** [comment]
This is not possible with how authentication is implemented in giscus, sorry. Maybe you can work something out if you self-host the application.

**Comment by AmazingAng** [comment]
Or how I can integrate the giscus authentication directly to my website?

**Comment by laymonage** [comment]
Sorry, I don’t think it’s possible either. GitHub requires specific redirect URLs in the configuration for each app, and specifying external URLs in the configuration for the giscus application itself would be a security risk.
