### ISSUE TITLE
reactions-menu button's icon not at center, iphone safari

### ISSUE THREAD

**Issue by yunyuyuan** [giscus/giscus#674]
![IMG_1100](https://user-images.githubusercontent.com/45785585/185789702-6e6f1b26-1ee1-452e-bc46-231a805633f0.png)

**Comment by laymonage** [comment]
Works fine here. Maybe try updating yours?

![telegram-cloud-photo-size-5-6057597071298507528-y](https://user-images.githubusercontent.com/6379424/185791532-d360fe4a-28cb-4911-932e-e4814f96b3dd.jpg)

**Comment by yunyuyuan** [comment]
> Works fine here. Maybe try updating yours?
> 
> ![telegram-cloud-photo-size-5-6057597071298507528-y](https://user-images.githubusercontent.com/6379424/185791532-d360fe4a-28cb-4911-932e-e4814f96b3dd.jpg)

Hmmm......Maybe its because my IOS or safari version.
