### ISSUE TITLE
Chrome is forcing a white background on iframe when the parent page has dark color-scheme meta

### ISSUE THREAD

**Issue by ceynri** [giscus/giscus#675]
I have been using giscus for over a year. Recently I noticed that the iframe of giscus has a white background when I use the dark theme on my page. 

![image](https://user-images.githubusercontent.com/37040496/185799573-0716aba0-6c6d-424d-a772-739c6057479f.png)

Then I found there is no problem when the parent page is in light theme. So I think this problem come from iframe. After search I found the discussion: <https://stackoverflow.com/questions/69591128/chrome-is-forcing-a-white-background-on-frames-only-on-some-websites>

The problem is that parent page in dark theme has the following meta while giscus' iframe doesn't have:

```html
<head>
  <meta name="color-scheme" content="dark" />
  <!-- ... -->
</head>
```

I use `"dark"` to make the browser's style in the dark theme. When the content is `"light"` ~~or `"light dark"`~~, there is no problem.

I noticed that giscus has set `color-scheme` to `normal` (Fix transparent background [#176](https://github.com/laymonage/giscus/pull/176)), which is the same solution as one of the answers to the [stackoverflow discussion](https://stackoverflow.com/questions/69591128/chrome-is-forcing-a-white-background-on-frames-only-on-some-websites
).

![image](https://user-images.githubusercontent.com/37040496/185801230-329bedd2-eea5-4391-b0ea-aa605bf4afb2.png)

The answer provided [a demo page](https://iframes-color-scheme.vercel.app/dark-light/with-no-scheme-iframe.html), but it doesn't seem to be able to fix the problem properly.

The answer:

![image](https://user-images.githubusercontent.com/37040496/185800577-4df057ed-3b38-466e-b5cf-f9de23f8c3e2.png)

What I see:

![image](https://user-images.githubusercontent.com/37040496/185800654-c6e7ac69-9b37-44ec-b9ca-286fd3fc98cf.png)

At last, I temporarily fixed the problem with the following style, which behaves as I expected, no more white background, both of light and dark color scheme on the parent page works correctly:

```css
#giscus::part(iframe) {
  color-scheme: light;
}
```

But I still don't fully understand why it works.

> Other reference articles I found: https://fvsch.com/transparent-iframes

**Comment by cbf66** [comment]
I think giscus is really rendering the component with whatever it's passed in the `data-theme="preferred_color_scheme"` attribute. Would be better, I think, to respect the current browser theme. (See [https://www.w3schools.com/jsref/met_win_matchmedia.asp](url). Perhaps if one simply leaves out the `data-theme` parameters. Hmm. This might already be the case?

**Comment by ceynri** [comment]
@cbf66 According to your suggestion, I continued to do some tests. I found some problems with the previous conclusions. In fact, when I set my win10 system to dark theme and add `<meta name="color-scheme" content="light dark" />` on the `<head>` of the parent page, giscus will also have this problem no matter how I set it. Neither is `data-theme="preferred_color_scheme"` attribute.

Here are some tests I did:

#### case 1
system theme: dark
head: `<meta name="color-scheme" content="light dark" />`
result: has white background

#### case 2
system theme: dark
head: `<meta name="color-scheme" content="light" />`
result: normal

#### case 3
system theme: dark
head: `<meta name="color-scheme" content="dark" />`
result: has white background

#### case 4
system theme: dark
head: no color-scheme meta
result: normal

#### case 5
system theme: light
head: `<meta name="color-scheme" content="light dark" />`
result: normal

#### case 6
system theme: light
head: `<meta name="color-scheme" content="dark" />`
result: has white background

Here is my guess:

When the case 1 or case 3, my computer system is in dark mode, and the page supports dark mode, so the browser thinks the page will use dark mode. In this case, because the giscus' iframe has no color-scheme meta, so the browser thinks gisucs' iframe only support light theme. So the browser will add a white background to the iframe to ensure that the contents (black text) of the iframe are clearly displayed.

The case 2, 3 and 5 is that the page is considered to use the light theme, so there is no problem.

So, add `<meta name="color-scheme" content="light dark" />` to giscus' iframe may solve the problem. But this requires practice and verification that the change will not create new problems.

> The meaning of `<meta name="color-scheme" content="light dark" />` is only that the page supports both of light and dark theme. It is also used on the GitHub page.
> ![image](https://user-images.githubusercontent.com/37040496/187932324-46a42909-a32f-421c-9238-cf5a154f1f18.png)

**Comment by Hacksore** [comment]
@laymonage This latest change seems to have given a default background color to my instance which was not happening before.

Live site https://boult.me/

Screenshot in case I find a good workaround and push it.
![image](https://user-images.githubusercontent.com/996134/200198104-730b7a4c-1eab-400a-8d7a-3217837bd484.png)

Embed options: https://github.com/Hacksore/Hacksore/blob/master/apps/web/src/pages/index.tsx#L28

**Comment by laymonage** [comment]
Sorry for the breaking change, this is a very tricky issue. I've basically been avoiding browsers' autodetection of `color-scheme`, but I think the best solution moving forward is to just correctly set the property.

Make sure your website sets the appropriate `color-scheme` in the styles, e.g.

```css
html {
  color-scheme: dark;
}
```

(I think you can also use `body` or `.giscus` as the selector.)

If your website supports light theme as well, make sure to set the `color-scheme` to `light` and update giscus theme using the suitable method for your installation.

**Comment by Hacksore** [comment]
@laymonage Not a problem, it happens. Adding the following meta tag is working locally to remove the background color.
![image](https://user-images.githubusercontent.com/996134/200198963-4b949588-2008-4be7-b992-031f11e9377b.png)

Another new behavior I've seen is that doing a hard reload the iframe seems to be white momentarily?

Contrived example where I'm only loading giscus to show the observation. 
![chrome_ascz6gyODq](https://user-images.githubusercontent.com/996134/200199040-aa087b44-c4ff-4c70-9ad1-db7689cbe642.gif)

**Comment by laymonage** [comment]
Argh, yeah, just noticed that. Seems that Chrome will always force a white background if the `color-scheme` isn't set to `light`. I've reverted the changes and used `color-scheme: light` instead of `color-scheme: normal`.

**Comment by laymonage** [comment]
Okay, should be fixed now...

**Comment by ameliacode** [comment]
Unfortunately, after some minor updates,
white background seems to appear...

adding meta tag didn't helped either.

**Comment by inwonakng** [comment]
I am having a similar issue. I want the giscus iframe to follow *only* the website's light/dark preference which I am handling by changing the data-theme passed into the iframe injection. But the injected iframe seems to somehow detect the OS's settings and follow it no matter what I set `data-theme` to. In the screenshots below, you can see that the data-theme is set to light and dark, but the displays are not reflecting it. 

Happening on Safari 16.4 and Chrome 112.0.5615.49 on MacOS Ventura 13.3.1.

OS: Dark mode, website: light mode:

<img width="1406" alt="Screenshot 2023-05-01 at 5 34 18 PM" src="https://user-images.githubusercontent.com/16977269/235535559-60bbde66-e21a-4748-832d-20757d3d4d22.png">

OS: Light mode, website: dark mode:
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/16977269/235535982-f9b7aa87-1eed-4c01-85fe-db7a5820be45.png">

**Comment by parimalyeole1** [comment]
![Screenshot 2023-05-16 at 2 42 27 AM](https://github.com/giscus/giscus/assets/16253408/2bc4ca6b-9aff-41e2-adc6-b6703385224b)
![Screenshot 2023-05-16 at 2 42 52 AM](https://github.com/giscus/giscus/assets/16253408/9df80c90-7d59-4504-a0bc-31ccf974f0ca)

I am trying to add giscus comments iframe to my blogs and iframe is completely transperant.

**Comment by HCY-ASLEEP** [comment]
I meet the same problem too when use dark reader in chrome. What surprise me is that it works well on MS-Edge. In fact, this issue have not closed yet.

![image](https://github.com/giscus/giscus/assets/76894615/153c0d28-99f6-4c48-8e9d-7930cceafe16)

Here is my site:

[https://hcy-asleep.github.io/Vim-ripgrep-quickfix-netrw-nmap-autocmd-wincmd-%E5%A4%A7%E6%9D%82%E7%83%A9/](https://hcy-asleep.github.io/Vim-ripgrep-quickfix-netrw-nmap-autocmd-wincmd-%E5%A4%A7%E6%9D%82%E7%83%A9/)

**Comment by ceynri** [comment]
@HCY-ASLEEP maybe you can try to add color-scheme meta to your html head.

```html
<head>
  <meta name="color-scheme" content="light dark" >
  <!-- ... -->
</head>
```

**Comment by HCY-ASLEEP** [comment]
> 

Okey, I will try. Thanks for your reply!

**Comment by Inori** [comment]
Same problem here.

Microsoft Edge
Version 114.0.1823.82 x64

No problem on firefox though.

**Comment by Inori** [comment]
Append `color-scheme: normal;` to the iframe style fix the problem.

**Comment by Prabhat-D-M** [comment]
Try doing this:
enableColorScheme={false} on next-themes (or removing color-scheme: dark from ) fixes the iframe/overlay rendering, and that dark mode works fine via CSS custom properties alone without the browser-level color-scheme hint.

I had a similar issue, this fixed it.
