### ISSUE TITLE
可以安装到wordpress 博客上面吗？

### ISSUE THREAD

**Issue by shutwin** [giscus/giscus#706]
可以安装到wordpress 博客上面吗？如何安装，有一键安装插件的方式吗？

**Comment by laymonage** [comment]
> Can I install it on a WordPress blog?

Yes

> How to install, is there a way to install the plugin with one click?

No, there's no plugin. Just follow the instructions on https://giscus.app/zh-CN and google "how to insert custom <script> tag on WordPress"

**Comment by shutwin** [comment]
谢谢回答 Thank you!
