### ISSUE TITLE
Usage issues on Blazor Server

### ISSUE THREAD

**Issue by NielsPilgaard** [giscus/giscus#740]
Hi there 👋 

When I add Giscus to my Blazor Server application, the discussion that is linked is always the same. I can work around the issue by removing and re-adding the <script> dynamically, but this causes an additional `client.js` file to be downloaded every time I render a page.

I'm fairly certain I must be doing something wrong, and was hoping you folks could point me in the right direction 😅 

Script used:
```js
<script src="https://giscus.app/client.js"
        data-repo="NielsPilgaard/Pilgaard.Blog"
        data-repo-id="R_kgDOIHUfWQ"
        data-category="Announcements"
        data-category-id="DIC_kwDOIHUfWc4CSFPf"
        data-mapping="pathname"
        data-strict="1"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="preferred_color_scheme"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>
```

Complete application: https://github.com/NielsPilgaard/Pilgaard.Blog/tree/giscus

**Comment by laymonage** [comment]
I'm not familiar with Blazor at all, but see if https://github.com/giscus/giscus-component/issues/32 and https://github.com/Jisu-Woniu/giscus-blazor might be helpful?

**Comment by NielsPilgaard** [comment]
That is exactly what I need, thanks a lot!
