### ISSUE TITLE
creating discussion not working in Next js

### ISSUE THREAD

**Issue by msamgan** [giscus/giscus#747]
<img width="1931" alt="image" src="https://user-images.githubusercontent.com/29948727/197945500-ca0318e2-35f1-4e21-8a98-1157d00c4eb6.png">

i am using  https://www.npmjs.com/package/@giscus/react 

please help.

**Comment by msamgan** [comment]
i have category id and repo id in the setup but its shwing empty in here..

**Comment by timrockefeller** [comment]
same issue, did you solve it yet?
