### ISSUE TITLE
Have a question about email cc?

### ISSUE THREAD

**Issue by zburu** [giscus/giscus#753]
>All replies under the same discussion will be cc'ed to everyone who has messaged here。

This is a feedback from one of my users. He once left a message on one of my articles, and every time others leave a message and my reply will be copied to his mailbox. I think this is unreasonable. Is there any way to improve this? What about the situation? Or where is giscus configured, and I didn't find it.

**Comment by nschonni** [comment]
Notifications/emails are from GitHub, not something configurable

**Comment by zburu** [comment]
> Notifications/emails are from GitHub, not something configurable

Thanks for the reply, I see, this is the mechanism of GitHub.
