### ISSUE TITLE
Wrong `preferred_color_scheme` color scheme

### ISSUE THREAD

**Issue by ouuan** [giscus/giscus#777]
After 664af3446ce13740130c9d62ab97fdccf5584a16, the `preferred_color_scheme` looks incorrect:

![screenshot](https://user-images.githubusercontent.com/30581822/201009842-343358e1-2658-438d-832a-373f67d2838b.png)

It seems that this is caused by https://github.com/giscus/giscus/blob/664af3446ce13740130c9d62ab97fdccf5584a16/client.ts#L118

My browser version is Mozilla Firefox 106.0.5.

**Comment by willyywt** [comment]
I think this should be set to `color-scheme: normal`

**Comment by willyywt** [comment]
Can't replicate this problem on Chromium 107

**Comment by willyywt** [comment]
Also not replicate on Firefox 102.4 ESR. Looks like this is not a bug but simply reveals a regression in Firefox

**Comment by willyywt** [comment]
Also not replicable on Firefox 102.4 ESR. Looks like this is not a bug but simply reveals a regression in Firefox

**Comment by ouuan** [comment]
> Also not replicable on Firefox 102.4 ESR. Looks like this is not a bug but simply reveals a regression in Firefox

Looks like a feature of Firefox 105: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/105#css

**Comment by willyywt** [comment]
> > Also not replicable on Firefox 102.4 ESR. Looks like this is not a bug but simply reveals a regression in Firefox
> 
> Looks like a feature of Firefox 105: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/105#css

Interesting, recent W3C standard makes embedded content inherit `color-scheme` from the embedding element, rather than resetting to browser defaults.

So its actually not a bug in Firefox but in other browsers, and in this issue, which set `color-scheme: light` for whatever reason? Because according to recent W3C standard, the html window in <iframe> should inherit `color-scheme` from the <iframe> element

**Comment by laymonage** [comment]
Did #785 fix it for you?

**Comment by willyywt** [comment]
[MDN - color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme)
`normal`: Use browser default. **Not necesarily related to `@media (prefers-color-scheme)` !** This is idential to `light` in most browser settings
`light`: Use light theme
`dark`: Use dark theme
`light dark`: Use either of light or dark theme. **The correct way to transparently pick up `@media (prefers-color-scheme)`**
`only light`, `only dark`: Disable "Auto Dark Theme" (Currently introduced in Chrome on Android, see [Chrome Developers](https://developer.chrome.com/blog/auto-dark-theme/#per-element-opt-out))
