### ISSUE TITLE
Use a release system

### ISSUE THREAD

**Issue by davidsneighbour** [giscus/giscus#778]
Several months back I started to implement Giscus on some of my websites. Now coming back to see what changed since then I can't find a "definite" way to see all updates listed since then. You are not using releases or versions and updates seem to be released whenever you commit a change with them being "live" immediately. It would be nice to have some form of release system where we add a version string to the setup so that this version is used and new features (or maybe breaking changes or fixes to issues that we solved locally somehow and might break with the fixes applied). 

I know this will add developer time, but it might be a useful addition to the tool for others too. The easiest way probably is to implement some form of version string to the setup with the latest version used when missing and then automatically create new versions at midnight via Github actions on days you have new commits - this way the "version aficionados" will be happy and you won't have too much work on your hands?

**Comment by ouuan** [comment]
There is a changelog: https://github.com/giscus/giscus/blob/main/CHANGELOG.md

I don't think you can choose to use an older version of giscus (maybe you can if you self-host it?), so I don't know how versioning would help. It's like adding versions to a website. Or are you requesting versioning for those who self-host giscus?

**Comment by davidsneighbour** [comment]
> Or are you requesting versioning for those who self-host giscus?

yes. but you are right, the CHANGELOG.md should suffice.
