### ISSUE TITLE
Inconsistent background color in both light and dark theme

### ISSUE THREAD

**Issue by krahets** [giscus/giscus#786]
The color setting worked well before but now it is not consistent with the web background.

The site was built by mkdocs-material.

<img width="775" alt="image" src="https://user-images.githubusercontent.com/26993056/201478898-14d683b9-8f7a-41e3-8be2-b224e89d43b1.png">

<img width="775" alt="image" src="https://user-images.githubusercontent.com/26993056/201478904-07884c42-7365-4c9a-b8d2-55485053986a.png">

Thanks!

**Comment by laymonage** [comment]
Fixed in #787, please report back if you're still having the issue. Thanks.

**Comment by AntoineSoetewey** [comment]
Hello,

not sure if this is linked, but here is what I see now:

![9A470A4F-9D9C-4275-8C8F-AC79E4362320](https://user-images.githubusercontent.com/17910063/201530447-9a8f7661-3410-42e4-8ef0-8db92cc0fb33.png)

I haven’t changed anything lately and this dark background wasn’t present so far.

thanks in advance!

**Comment by AntoineSoetewey** [comment]
For some unknown reasons, now at 4.46 PM it looks good. So you can ignore my previous message. I don’t know why it appeared different 10 minutes before.

**Comment by AntoineSoetewey** [comment]
For some unknown reasons, now at 4.46 PM it looks good:

![281B4096-9654-45A4-AC73-D71273611A9E](https://user-images.githubusercontent.com/17910063/201530837-d0222ff2-89a2-481f-a8c4-edc1c0c0cab5.png)

So you can ignore my previous message. I don’t know why it appeared different 10 minutes before.

**Comment by misode** [comment]
@laymonage This bug suddenly appeared on my site (https://misode.github.io/) without me changing anything. In both light and dark mode it shows a darker than usual background. Worth noting I use a custom style sheet. Do I need to make any changes myself to my custom css file?

**Comment by laymonage** [comment]
@misode You need to update your [`@giscus/react`](https://github.com/misode/misode.github.io/blob/master/package.json#L18) package to the latest version (2.2.3 at the time of writing).

**Comment by tisonkun** [comment]
It seems related to https://github.com/giscus/giscus-component/issues/914.
