### ISSUE TITLE
Custom theme not implementing as expected

### ISSUE THREAD

**Issue by EllaKaye** [giscus/giscus#789]
Hello,

I have light and dark giscus themes on my website and can toggle between them using the solution provided [here](https://github.com/giscus/giscus/issues/336#issuecomment-1214366281). I'd now like to use custom css to style the comments box. I think I've followed the instructions provided but it's not working as expected.

I have set up a test [repo](https://github.com/EllaKaye/quarto-test) and [site](https://serene-clafoutis-76cc16.netlify.app), with a comment box at the end of the [post](https://serene-clafoutis-76cc16.netlify.app/posts/welcome/).

I copied the [code](https://github.com/giscus/giscus/blob/main/styles/themes/light.css) for the light theme and saved it in the website project as `assets/giscus-light-custom.css` then changed a few of the color hexes, e.g.

```
  --color-btn-primary-bg: #D4006A;
```

In the script that toggles the theme, I set

```
  const giscusTheme = quartoTheme === "alternate" ? "dark" : "https://serene-clafoutis-76cc16.netlify.app/assets/giscus-light-custom.css";
```

The appearance of the giscus box has changed but my colors don't show. I would expect, for example, that the button is pink.

Have I missed something obvious? I would be grateful for your guidance.

**Comment by laymonage** [comment]
Looks like a CORS error:

<img width="999" alt="image" src="https://user-images.githubusercontent.com/6379424/201682138-a5c9e443-3d5e-44c0-aa2a-184ad9b92362.png">

Try adding the [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) header on your website:

https://docs.netlify.com/routing/headers/

**Comment by EllaKaye** [comment]
Thanks @laymonage for your speedy reply and pinpointing the problem. I will try and implement a solution and get back to you if I have any further questions.
