### ISSUE TITLE
Strange background style

### ISSUE THREAD

**Issue by hyoban** [giscus/giscus#792]
https://crawlee.dev/docs/quick-start

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/38493346/202603749-00eaf48b-78ac-452f-9bc0-2d3c20008ff2.png">

**Comment by hyoban** [comment]
it's ok in version 1.23

**Comment by laymonage** [comment]
You need to [upgrade your `@giscus/react` version](https://github.com/apify/crawlee/blob/b3d3c6a485552dc1b8ec1a492e161352b48d0dcf/website/package.json#L35), latest version is v2.2.4 at the time of this writing.
