### ISSUE TITLE
How to get id of the repo and the category?

### ISSUE THREAD

**Issue by CoolJosh0221** [giscus/giscus#806]
How to get id of the repo and the category?

**Comment by laymonage** [comment]
- Fill out the `repository` field:
  ![repository field](https://user-images.githubusercontent.com/6379424/174687333-930b4947-7033-458e-a207-827194751c9c.png)

- Select the category
  ![select category](https://user-images.githubusercontent.com/6379424/174687429-eb64b165-5ba9-4cc9-970f-3d3207a6f530.png)

- The values will show up automatically
  ![the ids show up automatically](https://user-images.githubusercontent.com/6379424/174687575-66435638-b719-4b62-b68c-642ffb511e56.png)
