### ISSUE TITLE
Post oauth/token 400

### ISSUE THREAD

**Issue by Sieboldianus** [giscus/giscus#809]
I am having issues since today:

<details><summary><code>widget-dfa89511f6fc81f4.js:1          POST https://giscus.app/api/oauth/token 400</code></summary>
<code>
(anonymous) @ widget-dfa89511f6fc81f4.js:1
(anonymous) @ main-e7f910b8a5ac3fbe.js:1
(anonymous) @ main-e7f910b8a5ac3fbe.js:1
i @ _app-250d8efaf3d95eb5.js:1
r @ _app-250d8efaf3d95eb5.js:1
(anonymous) @ _app-250d8efaf3d95eb5.js:1
(anonymous) @ _app-250d8efaf3d95eb5.js:1
q @ widget-dfa89511f6fc81f4.js:1
(anonymous) @ widget-dfa89511f6fc81f4.js:1
(anonymous) @ widget-dfa89511f6fc81f4.js:1
A @ framework-9592bd71dc410e47.js:1
w @ framework-9592bd71dc410e47.js:1
setTimeout (async)
t @ framework-9592bd71dc410e47.js:1
requestAnimationFrame (async)
R @ framework-9592bd71dc410e47.js:1
i.YM.diffed @ framework-9592bd71dc410e47.js:1
R @ framework-9592bd71dc410e47.js:1
E @ framework-9592bd71dc410e47.js:1
R @ framework-9592bd71dc410e47.js:1
E @ framework-9592bd71dc410e47.js:1
R @ framework-9592bd71dc410e47.js:1
E @ framework-9592bd71dc410e47.js:1
R @ framework-9592bd71dc410e47.js:1
E @ framework-9592bd71dc410e47.js:1
R @ framework-9592bd71dc410e47.js:1
E @ framework-9592bd71dc410e47.js:1
R @ framework-9592bd71dc410e47.js:1
E @ framework-9592bd71dc410e47.js:1
R @ framework-9592bd71dc410e47.js:1
E @ framework-9592bd71dc410e47.js:1
R @ framework-9592bd71dc410e47.js:1
E @ framework-9592bd71dc410e47.js:1
R @ framework-9592bd71dc410e47.js:1
E @ framework-9592bd71dc410e47.js:1
R @ framework-9592bd71dc410e47.js:1
E @ framework-9592bd71dc410e47.js:1
R @ framework-9592bd71dc410e47.js:1
E @ framework-9592bd71dc410e47.js:1
R @ framework-9592bd71dc410e47.js:1
E @ framework-9592bd71dc410e47.js:1
R @ framework-9592bd71dc410e47.js:1
E @ framework-9592bd71dc410e47.js:1
R @ framework-9592bd71dc410e47.js:1
E @ framework-9592bd71dc410e47.js:1
R @ framework-9592bd71dc410e47.js:1
E @ framework-9592bd71dc410e47.js:1
R @ framework-9592bd71dc410e47.js:1
O @ framework-9592bd71dc410e47.js:1
V @ framework-9592bd71dc410e47.js:1
fn @ framework-9592bd71dc410e47.js:1
h.default.createElement.callbacks @ main-e7f910b8a5ac3fbe.js:1
oe @ main-e7f910b8a5ac3fbe.js:1
(anonymous) @ main-e7f910b8a5ac3fbe.js:1
(anonymous) @ main-e7f910b8a5ac3fbe.js:1
(anonymous) @ main-e7f910b8a5ac3fbe.js:1
n @ main-e7f910b8a5ac3fbe.js:1
u @ main-e7f910b8a5ac3fbe.js:1
(anonymous) @ main-e7f910b8a5ac3fbe.js:1
(anonymous) @ main-e7f910b8a5ac3fbe.js:1
ue @ main-e7f910b8a5ac3fbe.js:1
ie @ main-e7f910b8a5ac3fbe.js:1
(anonymous) @ main-e7f910b8a5ac3fbe.js:1
(anonymous) @ main-e7f910b8a5ac3fbe.js:1
(anonymous) @ main-e7f910b8a5ac3fbe.js:1
n @ main-e7f910b8a5ac3fbe.js:1
u @ main-e7f910b8a5ac3fbe.js:1
Promise.then (async)
n @ main-e7f910b8a5ac3fbe.js:1
u @ main-e7f910b8a5ac3fbe.js:1
Promise.then (async)
n @ main-e7f910b8a5ac3fbe.js:1
u @ main-e7f910b8a5ac3fbe.js:1
Promise.then (async)
n @ main-e7f910b8a5ac3fbe.js:1
u @ main-e7f910b8a5ac3fbe.js:1
(anonymous) @ main-e7f910b8a5ac3fbe.js:1
(anonymous) @ main-e7f910b8a5ac3fbe.js:1
ce @ main-e7f910b8a5ac3fbe.js:1
t.hydrate @ main-e7f910b8a5ac3fbe.js:1
(anonymous) @ main-e7f910b8a5ac3fbe.js:1
Promise.then (async)
318 @ main-e7f910b8a5ac3fbe.js:1
n @ webpack-3a1430c391863fce.js:1
(anonymous) @ main-e7f910b8a5ac3fbe.js:1
n.O @ webpack-3a1430c391863fce.js:1
(anonymous) @ main-e7f910b8a5ac3fbe.js:1
e @ webpack-3a1430c391863fce.js:1
(anonymous) @ main-e7f910b8a5ac3fbe.js:1
</code>
</details>
<code>
client.js:7 [giscus] An error occurred. Error message: "State has expired.". Please consider reporting this error at https://github.com/giscus/giscus/issues/new.
</code>

**Comment by laymonage** [comment]
Ah, I think it's just a stale state stored in the `localStorage`. Does reloading and logging back in work?

**Comment by Sieboldianus** [comment]
Yes, looks like it is working again. I just went to the side and the comments appear again. Many thanks for the quick response!

❤️ 

Closing this..
