### ISSUE TITLE
Under giscus, add "Comment options" to the message

### ISSUE THREAD

**Issue by zkitefly** [giscus/giscus#821]
> Note: The title and content are translated by deepl.com

The functions described are the picture functions demonstrated below:
- Report content message
- Edit message
- Delete message
- Copy the Discussions link for this message
- Quote reply message
![image](https://user-images.githubusercontent.com/64117916/206913599-0d32f641-b8fd-4d0c-b4ee-e8091d6ccbea.png)
- Edited message history
![image](https://user-images.githubusercontent.com/64117916/206913736-37c36ddf-3b60-4190-b337-d254d20eb24e.png)
- The markdown toolbar of the message box
- Attach files / photo by dragging & dropping, selecting or pasting them
![image](https://user-images.githubusercontent.com/64117916/206913775-1b3d95bc-4bde-44f2-9a68-2ae36dc609a6.png)

Adding these options and features as shown above makes me like giscus even more because it makes me more comfortable in commenting, like this:
![](https://github.com/zkitefly/myphoto/raw/173dbb5c6616352adb4655aa032ffe5724affd61/%E5%BD%95%E5%B1%8F_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20221211233019.gif)

------------------------------------

所述的功能为以下演示的图片功能：
The functions described are the picture functions demonstrated below:
- Report content message
- Edit message
- Delete message
- Copy the Discussions link for this message
- Quote reply message
![image](https://user-images.githubusercontent.com/64117916/206913599-0d32f641-b8fd-4d0c-b4ee-e8091d6ccbea.png)
- Edited message history
![image](https://user-images.githubusercontent.com/64117916/206913736-37c36ddf-3b60-4190-b337-d254d20eb24e.png)
- The markdown toolbar of the message box
- Attach files / photo by dragging & dropping, selecting or pasting them
![image](https://user-images.githubusercontent.com/64117916/206913775-1b3d95bc-4bde-44f2-9a68-2ae36dc609a6.png)
添加如上图的这些选项和功能，我就更加喜欢giscus，因为它能让我在评论中更加舒服，就像这样：
![](https://github.com/zkitefly/myphoto/raw/173dbb5c6616352adb4655aa032ffe5724affd61/%E5%BD%95%E5%B1%8F_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20221211233019.gif)

**Comment by laymonage** [comment]
See #36, #84, #197. Other things like the markdown toolbar I might consider in the future. However, honestly, in addition to the complexity of the features, I'd rather keep the widget simple and lightweight, as the features you're asking for can be reached quite easily by clicking the timestamp to open the discussion on GitHub.

**Comment by aayushdutt** [comment]
@laymonage Delete should be a very basic option that must be available, if not edit. If someone accidentally adds something they should really be able to delete their comment. It's not clear at all that clicking on the timestamp will lead you to the discussion page to me. For the commentors - who don't know this is using github discussions, there's no way they'll know how to delete it.

**Comment by laymonage** [comment]
PRs welcome.
