### ISSUE TITLE
Error message: "State has expired." - Giscuss could not display

### ISSUE THREAD

**Issue by MountAye** [giscus/giscus#823]
An example page: [https://mountaye.github.io/blog/articles/python-decorator](https://mountaye.github.io/blog/articles/python-decorator)

My blog is a GitHub Pages for a repo `blog` rather than `mountaye.github.io`, so I build locally with `bundle exec jekyll build` and push `_site` folder onto GitHub.

I had been successful using giscus for some time, but recently (no earlier than Nov 17, 2022) the comments cannot display on any of the pages. The browser console shows the following message:  

```
[giscus] An error occurred. Error message: "State has expired.". Please consider reporting this error at https://github.com/giscus/giscus/issues/new. [client.js:7:210](https://giscus.app/client.js)
    <anonymous> https://giscus.app/client.js:7
```

I've updated the `<script>` block to the newest version, but it still does not work:
```html
  <script src="https://giscus.app/client.js"
          data-repo="MountAye/blog"
          data-repo-id="R_kgDOGc3UIA"
          data-category="Comments"
          data-category-id="DIC_kwDOGc3UIM4CAI4h"
          data-mapping="title"
          data-strict="0"
          data-reactions-enabled="1"
          data-emit-metadata="0"
          data-input-position="bottom"
          data-theme="light"
          data-lang="zh-CN"
          crossorigin="anonymous"
          async>
  </script>
```

=================================

BTW, I can see giscus on the local test with `bundle exec jekyll serve -w`

**Comment by MountAye** [comment]
Clearing the browser cache solves the problem. Sorry for bothering.

**Comment by laymonage** [comment]
Thanks for the report! This is actually a valid issue (though I believe #809 is the same issue), I forgot to make it so that the client script clears the session if it has expired. Should be fixed now.

I'll port the fix to [giscus-component](https://github.com/giscus/giscus-component) sometime later this week.
