### ISSUE TITLE
Add comment initialization mechanism similar to GiTalk

### ISSUE THREAD

**Issue by Xheldon** [giscus/giscus#840]
Giscus is a great project, but its initialization and user authorization comments rely on third-party services is the only thing I worry about, because the stability of third-party services is always unreliable, especially in some countries with network blockades, and this is the only reason I didn't switch from gitalk to giscus.

Hoped to add a comment initialization mechanism similar to GiTalk, which is limited to the repository owner to initialize comments, so as to avoid relying on third-party servers.

**Comment by laymonage** [comment]
Could you elaborate on what you mean by “comment initialization”? If what you mean is “creating a new discussion the first time someone leaves a comment”, you don’t need to wait until someone does so. You can create the discussion manually through GitHub (or automate it through GitHub’s API). As long as the title mapping matches, giscus will be able to find the discussion.

**Comment by Xheldon** [comment]
Thanks for the reply! @laymonage 
Maybe my description of comment initialization is misleading you, but I do find this to be where giscus differs from gitalk.

And my real purpose is to send requests directly to GitHub without relying on any third-party services, can this be done through GitHub's Discussions API? Just like gitalk: 

![CleanShot_2023_01_05_at_08_48_24@2x](https://user-images.githubusercontent.com/9780154/210677024-a52dfe51-d3a8-4f74-960b-e4313c2dd474.png)

because I've observed websites that use Giscus and find that they all request giscus.app:

![CleanShot_2023_01_05_at_08_49_17@2x](https://user-images.githubusercontent.com/9780154/210677108-8499cccc-ad09-4b56-bb42-167714a913a9.png)

BTW, I didn't think issue was a good option as a blog comment, So I decided to try Giscus, but using a third-party service made me back, because, you know, in some areas people don't have that smooth access to the Internet.

Any idea?

**Comment by laymonage** [comment]
Ah, I see. I would love to make it so that the requests are sent directly to GitHub, but this just isn’t possible for now because the Discussions API is only available through GraphQL and the GraphQL requires authentication for all requests. This means that visitors won’t be able to see the comments without logging in.

Proxying the API call through our own server allows us to authenticate as the app itself when the user has not signed in, which makes it possible to use the API.
