### ISSUE TITLE
How to disable resizing of iframe height ??

### ISSUE THREAD

**Issue by NithinKuruba** [giscus/giscus#851]
I am rendering multiple discussions in form of giscus widgets in my react app. Each giscus widget is a child of an `Accordion` component created using `react-bootstrap`. When I open one accordion component to view giscus widget, the height of the iframe of already opened one re-adjusts and gets cropped, which is a weird behaviour. Is there a way to stop this resizing of the iframe height??

**Comment by laymonage** [comment]
Answered in https://github.com/giscus/giscus-component/issues/980.
