### ISSUE TITLE
All commenters get the message

### ISSUE THREAD

**Issue by chrisyy2003** [giscus/giscus#852]
Does a person who just replied to an article get a message afterward, even if it wasn't directly replied to him?

**Comment by laymonage** [comment]
If what you mean by a "message" is a GitHub notification, then yes, that's how it works on GitHub by default. It's something that's out of our control.

**Comment by chrisyy2003** [comment]
Is there anything I can do to set it up, my friend just told me he got dozens  replies which is not reply to him，

<img width="593" alt="image" src="https://user-images.githubusercontent.com/63803385/212102248-2b77938e-4633-47f6-b94a-2e9f294662c0.png">

**Comment by laymonage** [comment]
Your friend can open the discussion on GitHub and click on "Unsubscribe" on the right sidebar. Example:

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/6379424/212125387-e5dbe831-379a-40d5-b1d9-02bd0bc3c2ae.png">
