### ISSUE TITLE
Refused to frame 'giscus.app' .... "frame-ancestors 'self'"

### ISSUE THREAD

**Issue by mcsmonk** [giscus/giscus#868]
I'm trying to embed giscus in [https://sunghyunjin.com/blogwiki](https://sunghyunjin.com/blogwiki).

However, giscus.app refused to connection. I found the following error message in the chrome development tool.
>Refused to frame 'https:\/\/giscus.app' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".

I surveyed related issues, e.g., #721, and had tried to solve this problem based on that, but I didn't solve it yet.

Here are links to related files.
1. config for giscus [link](https://github.com/mcsmonk/blogwiki/blob/master/_config.yml)
1. giscus.json [link](https://github.com/mcsmonk/blogwiki/blob/master/giscus.json)
2. script for embedding comment [link](https://github.com/mcsmonk/blogwiki/blob/master/_includes/comment.html)
3. an example page [link](https://sunghyunjin.com/blogwiki/wiki/how-to/ipynb/), [src](https://github.com/mcsmonk/blogwiki/blob/master/_wiki/how-to/ipynb.md)

**Comment by laymonage** [comment]
Works just fine here?
<img width="860" alt="image" src="https://user-images.githubusercontent.com/6379424/215162224-012eb595-e3d7-4786-bcbd-6a0fe8ee5dde.png">

**Comment by laymonage** [comment]
Ah, you've fixed it in https://github.com/mcsmonk/blogwiki/commit/047cfa6c500dc38161dd55b73aa9cc5c2ea824e6

See:
- https://github.com/giscus/giscus/issues/833#issuecomment-1379545547
- https://github.com/giscus/giscus/issues/380#issuecomment-1026328308

**Comment by oldeightLB** [comment]
Is this issue affecting everyone worldwide? I thought it was only a problem in China.

**Comment by mcsmonk** [comment]
> Is this issue affecting everyone worldwide? I thought it was only a problem in China.

I'm Korean. So, maybe not
