### ISSUE TITLE
Applying custom theme

### ISSUE THREAD

**Issue by sciarraseb** [giscus/giscus#880]
I am trying to apply a custom theme that I made (it is currently in a PR). The CSS file that I would like to use can be found  [here](https://github.com/sciarraseb/giscus/blob/main/styles/themes/cobalt.css).  I have tried using the following code with a URL to the CSS file (as suggested in the [documentation](https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md)) and have not succeeded in applying the desired color scheme to my comments section. When I try to apply the custom theme, all the colors in my giscus comments section go white.  I suspect I might be missing some rudimentary component and so any help is appreciated! 

```
<script src="https://giscus.app/client.js"
        data-repo="sciarraseb/HugoWebsite"
        data-repo-id="R_kgDOIwrh4A"
        data-category="Comments"
        data-category-id="DIC_kwDOIwrh4M4CT1kX"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="https://github.com/sciarraseb/giscus/blob/main/styles/themes/cobalt.css"
        data-lang="en"
        crossorigin="anonymous"
        async>
</script>
```

**Comment by laymonage** [comment]
See https://github.com/giscus/giscus/discussions/877

**Comment by sciarraseb** [comment]
Perfect! Thank you very much. I got it working by setting `data-theme` with JSDelivr's CDN. If any future users find this helpful, this is the structure to use for the `data-theme` entry: 
```
https://cdn.jsdelivr.net/gh/<github-username>/<github-repo>@<commit-id>/<file-path>
```
where the `file-path` is relative to the root of the repository and `commit-id` is the commit ID for the file that needs to be served. 

This results in the following entry for the `data-theme` field: 

```
 data-theme="https://cdn.jsdelivr.net/gh/sciarraseb/giscus@8cdfe5ff92c061ae8f8f3528299a0d5610530e8c/styles/themes/cobalt.css"
```

**Comment by nifanle7** [comment]
> Perfect! Thank you very much. I got it working by setting `data-theme` with JSDelivr's CDN. If any future users find this helpful, this is the structure to use for the `data-theme` entry:完善！谢谢。我通过使用 JSDelivr 的 CDN 进行设置 `data-theme` 来让它工作。如果任何未来的用户发现这有帮助，这是用于 `data-theme` 条目的结构：
> 
> ```
> https://cdn.jsdelivr.net/gh/<github-username>/<github-repo>@<commit-id>/<file-path>
> ```
> 
> where the `file-path` is relative to the root of the repository and `commit-id` is the commit ID for the file that needs to be served.其中 是相对于存储库的根目录， `commit-id` 是 `file-path` 需要提供的文件的提交 ID。
> 
> This results in the following entry for the `data-theme` field:这将导致该 `data-theme` 字段的以下条目：
> 
> ```
>  data-theme="https://cdn.jsdelivr.net/gh/sciarraseb/giscus@8cdfe5ff92c061ae8f8f3528299a0d5610530e8c/styles/themes/cobalt.css"
> ```

I tried so many ways to load my custom css url, but it always alert CORS at console. However, I use other bloggers' custom css url, it just works. I feel weird and upset. Fortunely, this way works. Thank you so much!
