### ISSUE TITLE
404 error when loading the widget.

### ISSUE THREAD

**Issue by white-gorilla** [giscus/giscus#900]
I'm sorry to ask for your help.
I looked in the issues to see if I could find a similar anomaly.

I'm trying to integrate the commenting system on our [blog](https://ai.lefebvre-sarrut.eu/).

- I did make the repo public.
- I installed the Giscus app and selecting the repo.
- I have activated the repo discussion system.
- I have created a discussion type category dedicated to [Giscus](https://github.com/ELS-RD/ai.lefebvre-sarrut/discussions/categories/_)
- I overrided the [partial `overrides/partials/comments.html` with the following script and configuration](https://github.com/ELS-RD/ai.lefebvre-sarrut/blob/main/docs/overrides/partials/comments.html).
```
<script src="https://giscus.app/client.js"
        data-repo="ELS-RD/ai.lefebvre-sarrut"
        data-repo-id="R_kgDOIyxsZw"
        data-category="_"
        data-category-id="DIC_kwDOIyxsZ84CUH5n"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="dark"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>
```
- Finally, I have created the [configuration file `giscus.json` so that it works on our domain and locally](https://github.com/ELS-RD/ai.lefebvre-sarrut/blob/main/giscus.json).
```
{
  "origins": [
    "https://ai.lefebvre-sarrut.eu"
  ],
  "originsRegex": [
    "http://localhost:[0-9]+"
  ]
}
```

The widget is well placed, but launches a request that returns a 404.
Ex. [here](https://ai.lefebvre-sarrut.eu/2020/05/20/divide-hugging-face-transformers-training-time-by-2-or-more-with-dynamic-padding-and-uniform-length-batching/#a-conclusion).

I can't figure out why, instead of loading the widget, my own 404 page is inserted instead.

When I look at the failed query and compare it to other sites, I don't feel like it's correct.
Shouldn't it target giscus.app?

The example query that returns a 404.

https://ai.lefebvre-sarrut.eu/en/widget?origin=https://ai.lefebvre-sarrut.eu/2020/05/20/divide-hugging-face-transformers-training-time-by-2-or-more-with-dynamic-padding-and-uniform-length-batching/#a-conclusion&session=&theme=dark&reactionsEnabled=1&emitMetadata=0&inputPosition=top&repo=ELS-RD/ai.lefebvre-sarrut&repoId=R_kgDOIyxsZw&category=_&categoryId=DIC_kwDOIyxsZ84CUH5n&strict=0&description=A+blog+fully+dedicated+to+AI+at+Lefebvre+Sarrut&backLink=https://ai.lefebvre-sarrut.eu/2020/05/20/divide-hugging-face-transformers-training-time-by-2-or-more-with-dynamic-padding-and-uniform-length-batching/#a-conclusion&term=2020/05/20/divide-hugging-face-transformers-training-time-by-2-or-more-with-dynamic-padding-and-uniform-length-batching/

Thank you for your help.

**Comment by laymonage** [comment]
Your build system seems to collect the javascript and host it on your own website:

<img width="456" alt="image" src="https://user-images.githubusercontent.com/6379424/218445470-55276b97-fcbb-4957-ad6b-78e2615f8d51.png">

The script uses the `src` attribute's `origin` to determine the host of the giscus server:

https://github.com/giscus/giscus/blob/e3d25f29d39613153a120060727c8bd90becf04f/client.ts#L4

This was done so that the iframe automatically picks up the domain for self-hosted instances of giscus, and also to make it easier for me to test locally.

One workaround for now is see if you can disable the automatic conversion of the script's `src` on your build system.

I'll see if there's a better way to detect the target iframe's origin later.

**Comment by white-gorilla** [comment]
Thanks @laymonage. 

I have actually installed the `privacy` plugin which allows to automatically fetch external assets. It is possible to exclude assets that should not be affected. That's what I did and it works. I understand that the Material 4 MkDocs documentation doesn't explicitly give this information... although it does give us a little hint.

Thanks @laymonage, **great job**.
