### ISSUE TITLE
Page scrolling disabled 

### ISSUE THREAD

**Issue by MountAye** [giscus/giscus#901]
The page cannot scroll when the mouse is hovering on the components of Giscus.

Usually this is not a serious problem, but for [this page](https://mountaye.github.io/blog/Comments/), the scroll bar just disappears and scrolling does not work wherever the mouse is. Zoom in and out the page could solve the problem, but it's inconvenient to teach the users.

I don't know if this comes from Giscus or my Jekyll template, could you check it out?

**Comment by laymonage** [comment]
Remove `overflow: hidden;` from your HTML.

https://user-images.githubusercontent.com/6379424/219743147-0b4b30a0-ee6e-454a-9529-b1e6cf33d414.mov
