### ISSUE TITLE
help wanted to start dev mode

### ISSUE THREAD

**Issue by nagy-nabil** [giscus/giscus#921]
it might be silly but that's my problem right now i downloaded from the private key from github, but i'm having hard times convert it to the required structure 
i tried this command `openssl rsa -in your_private_key_file.pem -outform PEM > github_private_key.pem`
but still get the same error `An error occurred: secretOrPrivateKey must be an asymmetric key when using RS256`

so i need help to convert the key, thanks in advance

**Comment by laymonage** [comment]
What do you mean you need to convert it to the required structure? I think you should be able to use it as-is.

**Comment by nagy-nabil** [comment]
this the default application to open pem files in ubuntu and i didn't try another app to open but i get it thank you
![image](https://user-images.githubusercontent.com/65990275/222124210-77dfa1af-e4ac-42db-8e06-d876b4864779.png)

still i got another problem now `An error occurred: giscus is not installed on this repository`

and when using my fork as the repo `nagy-nabil/giscus` i got the error `Cannot use giscus on this repository. Make sure all of the above criteria has been met.` and i did the steps above but ofc using my github app not giscus itself

**Comment by nagy-nabil** [comment]
i just saw your comment in #491  [comment link](https://github.com/giscus/giscus/issues/491#issuecomment-1099820231), and what i understand is i need to deploy my self-hosted application  to be able to use it for local development 
can you please describe  the local development process more
