### ISSUE TITLE
Translation error on Spanish for "Comment" button

### ISSUE THREAD

**Issue by zogar1993** [giscus/giscus#951]
Buttons should use verbs instead of nouns. The verb for "Comment" in Spanish is "Comentar". The current value "Comentario" is the noun, which feels really weird in a button.

I expect this to be as simple as modifying the common.json for Spanish, setting "comment" value to "Comentar" instead of "Comentario".

**Comment by laymonage** [comment]
Feel free to send a PR! 😃
