### ISSUE TITLE
GitHub logged in status not detected, still asked to sign in with GitHub

### ISSUE THREAD

**Issue by dandv** [giscus/giscus#957]
New to Giscus. I've installed the widget in [our Docusaurus staging environment](https://6419e73f5718e309249a231a--tangerine-buttercream-20c32f.netlify.app/developers/weaviate/api/graphql/aggregate) using `@giscus/react`, and noticed the "Sign in with GitHub" button. I'm already signed into GitHub. Any way to detect that, the way the Facebook comments widget does, cross-origin?

I know giscus needs to obtain user permissions from GitHub to act on their behalf, but the "Sign in with GitHub" wording might suggest the widget hasn't detected that the user is signed into GitHub already. Maybe "Sign into Giscus with GitHub" would be clearer, since the user knows they haven't signed *into Giscus* yet?

![image](https://user-images.githubusercontent.com/33569/226666779-161a1bed-144d-42a6-b11f-9b14543d2ddc.png)

**Comment by laymonage** [comment]
> Any way to detect that, the way the Facebook comments widget does, cross-origin?

Unfortunately, no. Facebook's comments widget is first-party, so it can reuse the cookies.

I think "Sign in with GitHub" is clear enough, the keyword is **"with"** (i.e. it doesn't read "Sign _into_ GitHub").

"Sign into giscus with GitHub" is too verbose for the button, so thanks for the suggestion but I'm not going to accept it.
